== La Vida de James Parnell

James Parnell nació en Retford, en Nottinghamshire, en 1637.
No es fácil averiguar la posición social exacta de la vida en la cual él se movió.
Se dice en la orden judicial por la cual fue entregado al castillo de Colchester,
que él era un "`trabajador.`"
Él dice de sí mismo que estaba ocupado en su "`vocación externa,`"
cuando no estaba ocupado en el servicio de la Verdad;
y que "`no pretendió tener ninguna propiedad en la tierra.`"
Es por lo tanto probable, que sus circunstancias fueran humildes.
Nuestro historiador, William Sewel,
nos informa que fue "`adiestrado en las escuelas de literatura,`" una
declaración probablemente derivada de una observación de James Parnell,
que fue "`enviado a escuelas de aprendizaje humano para aprender la sabiduría humana;
para cuyo fin las escuelas son útiles.`"
Sin embargo, sus escritos parecen indicar que,
aunque había recibido una educación más allá de lo común en aquellos días, era limitada;
y ciertamente no se extendió más allá de su decimocuarto año. Henry Tuke, con razón,
supone que pudo haber recibido instrucción en la Escuela de Gramática de Retford;
y es muy probable que la siguiente observación de
James Parnell se refiera a los autores clásicos:
"`Muchos de los libros que se leen en las escuelas de aprendizaje humano hacen
mucho por corromper a la juventud y nutrir la naturaleza salvaje y profana,
que entonces gobernaba en mí.`"

Él comienza así un breve relato, que escribió en el castillo de Colchester,
de su experiencia religiosa: "`En primer lugar,
daré al lector una declaración de la obra de Dios en mi alma y
la conversión de mi corazón de las tinieblas a Su maravillosa luz;
del poder de Satanás hacia Dios; del camino de la muerte hacia el camino de la vida,
donde ahora ando en la luz de mi Dios,
con los rescatados del Señor que están viajando hacia la ciudad santa;
y también la razón de mi venida al mundo para declarar la Verdad,
por la cual ahora sufro el cautiverio por la generación perseguidora.`"
Él dice que fue una vez un "`hijo de ira`" como todos son por naturaleza,
y siguió los caminos vanos del mundo.
Sus perversas propensiones naturales se alimentaban de la educación que recibía;
de modo que, mientras estaba en la escuela, y después de abandonarla,
permaneció la misma depravación de corazón y creció en pecado
y continuó siguiendo las vanidades pecaminosas del mundo.
Fue adiestrado en la adoración que se acostumbraba
en la nación y asistía al servicio los primeros días;
pero como sus ejercicios religiosos no estaban asociados con ninguna conversión
real de corazón y fueron emprendidos en su propia voluntad carnal,
él después los consideró como mera idolatría.

Pero, aun en esta época, mientras estaba alejado en su corazón de Dios,
y siguiendo las gratificaciones de la mente carnal, era, de vez en cuando,
sensible a las visitaciones de la luz celestial; sin saber su origen celestial,
porque al principio "`brillaba en la oscuridad,`"
sin entender de dónde venía o hacia dónde iba.
Esto brotaba en su corazón cuando estaba solo,
y lo reprendía en secreto por sus transgresiones;
por lo cual él a menudo era guiado a un serio examen
de sí mismo y a la consideración de sus caminos;
y la vida y la muerte fueron a veces puestas delante de sus ojos de tal manera,
que lo hizo tomar la decisión de abandonar el pecado.
Pero ignorando que estos "`reproches e instrucciones`"
eran las luchas del Espíritu de Verdad con él,
y no sabiendo todavía que toda fuerza y suficiencia
para vencer al pecado solo se derivaban de Dios,
estas determinaciones las hacía en su propia voluntad,
y se mantenían solo hasta que sus resoluciones eran probadas por alguna nueva tentación,
cuando la mente descuidada otra vez vagaba,
y "`lo llevaba todavía a deleitar su corazón en la vanidad,
que el ojo veía y el oído oía.`"

Pero el placer derivado de tales vanidades pasó con el uso,
y fue dejado con nuevos juicios por su transgresión;
porque el Espíritu de Verdad todavía lo seguía,
"`lo convenció de pecado`" y lo llamó al arrepentimiento y a la corrección de la vida.
Cuanto más inclinaba su mente y se acercaba a Dios, en estas manifestaciones internas,
descubría que Dios se acercaba a él,
de modo que al fin él confesó con gran gratitud que "`Él fue hallado por
Él cuando no lo buscaba;`" porque él sentía que era la bondad gratuita,
inmerecida y no solicitada del Señor hacia él,
"`el mayor de los pecadores,`" que lo llamaba al arrepentimiento
y con el tiempo operó también una reforma de corazón;
trabajando así en él "`tanto el querer como el hacer,`"
y arrancándolo como un hierro de las llamas,
para hacer de él un instrumento de honor en Su casa.

James Parnell declaró que él era, según su edad,
"`tan perfecto en el pecado`" como cualquiera en la ciudad donde
él vivía y que excedió a muchos en la maldad de su vida.
En este estado,
él era amado por los de mentalidad mundana que estaban a su alrededor como uno de ellos.
Pero cuando el Señor se "`complació en dar a conocer su poder en él,
y dirigir su corazón hacia Él,
para que verdaderamente lo buscara,`" el cambio que fue hecho por la gracia divina,
lo convirtió en una maravilla para ellos,
y lo odiaron y se apartaron de él en su estado convertido,
tanto como lo habían buscado mientras él llevaba una vida impía. Incluso sus parientes,
estando en esa mente carnal que "`no entiende las cosas del Espíritu,`" trataron de
alejarlo de la fidelidad a Dios y destruir la obra que Él había comenzado en su corazón.
Y cuando ellos no pudieron prevalecer sobre él para conformarlo al mundo en sus "`modas,
costumbres, tradiciones, caminos, compañerismo y adoración`" (porque su ojo,
habiendo sido abierto por el poder de Dios,
percibió la idolatría de tales cosas y ya no podía practicarlas),
se convirtieron en sus mayores enemigos, e incitaron la persecución contra él,
de modo que se convirtió en "`una burla en las calles`"
y se consideró indigno de vivir entre ellos,
y algunos incluso dijeron: rendiría servicio a Dios matarlo.

"`Pero,`" este joven dedicado dice, "`El que me llamó de entre ellos, a Sí Mismo,
para que ya no siguiera más los caminos vanos del mundo,
ni pusiera mi deleite en las cosas de abajo, sino que le sirviera en novedad de vida,
para que en mí Su obra pudiera aparecer para confundir a los paganos que no lo conocían,
me mantuvo por Su poder y me dio fuerzas para soportar Su cruz y despreciar la vergüenza;
para que ni las palabras dulces ni las palabras desagradables pudieran
hacerme negar lo que Dios por Su gracia había hecho en mi corazón.`" Y
sintiendo la preciosidad de ser llevado a la relación espiritual con su
Padre celestial,--sintiendo el incomparable valor de ser un hijo de Dios,
y si hijo, heredero, heredero de Dios y coheredero con Cristo,
se dispuso y salió de su parentela y "`se convirtió
en un extraño para los que no amaban la Verdad.`"

La verdadera conversión de su alma,
evidenciada por un andar que coincidió con la alta vocación con que fue llamado,
tuvo el efecto de manifestar claramente el carácter mundano de los sacerdotes,
a cuyo ministerio había estado acostumbrado a asistir.
Mientras vivía en la vana conducta del mundo,
no lo tomaron en cuenta ni para reprenderlo ni para instruirlo,
porque ellos estaban metidos tan profundamente en el espíritu del mundo como otros.
De hecho,
ellos sostenían con sus vidas y conductas el mismo mal que condenaban en sus sermones,
y así se descalificaban para trabajar en la conversión de los miembros
individuales del rebaño. Condenaban el pecado en general,
pero temían hablar en contra de él en casos particulares,
para no levantar críticas sobre sus propias vidas.
Pero tan pronto como James Parnell manifestó un caminar más cercano con Dios,
y que estaba seria y verdaderamente del lado de Dios,
y tan pronto como sus frutos manifestaron que había sido injertado
en la Vid verdadera y participaba de su savia viva,
entonces ellos se convirtieron en sus enemigos y dijeron "`él fue engañado.`"
Cuando James Parnell encontró que los sacerdotes eran carnales,
y (junto con la gente que los seguía) tenían solamente la forma externa,
mientras negaban la vida y el poder de la verdadera religión,
se apartó de ellos y buscó un pueblo con el cual pudiera tener unidad.

George Fox ya en 1643 había dejado sus relaciones
y se dedicó a su misión de manera privada;
pero no fue sino hasta 1648 que empezó su ministerio de una manera extensamente pública,
en cuyo momento él dice: "`Diversas reuniones de Amigos, en varios lugares,
fueron reunidos a las enseñanzas de Dios, por Su luz, espíritu y poder.`"
La gran obra que se ha mencionado progresivamente en la mente de James Parnell,
y el paso decisivo de separarse del modo de culto nacional,
tuvo lugar antes de los quince años de edad, es decir,
antes de 1652 y por aquel tiempo los Amigos deben haber sido conocidos como un pueblo.
Sin embargo, no había Amigos en el lugar donde vivía James Parnell,
y hasta ese momento no había tenido ninguna interacción
con ninguno de aquellos a los que se unió posteriormente,
como a un pueblo que se reunía para "`adorar a Dios en Espíritu,
regocijarse en Cristo Jesús y no tener confianza en la carne.`"
De sus propios escritos se desprende claramente que la obra
fue una obra de Dios solamente por su Espíritu en su corazón;
y él constituye uno de los muchos casos que abundan
en la primera época de la historia de nuestra Sociedad,
de aquellos que, sin comunicación con los demás,
fueron guiados por el mismo Espíritu para adoptar
algunos de los principios más importantes de la Verdad.

Parece probable que esto fue en el año 1651, a la edad de catorce años,
cuando se separó de los profesantes carnales y buscó un
pueblo con el que pudiera unirse en comunión religiosa.
Él dice:
"`había un pueblo con el que encontré unidad a pocos
kilómetros de la ciudad donde yo vivía,
a quien el Señor estaba reuniendo fuera del mundo oscuro,
para sentarse juntos y esperar en Su nombre.`"
Con ellos él soportaba "`el oprobio de Cristo`" y estaba dispuesto por Su causa,
a ser contado entre los que eran considerados como "`la escoria del mundo`" (1 Cor.
4:13); pero en sus aflicciones y persecuciones por causa del Salvador,
se regocijaban al recordar que estaba escrito que los que vivieran piadosamente en Él,
sufrirían persecución; y consideraban una mayor riqueza ser Su pueblo,
y sufrir el odio y el desprecio de todos,
que gozar "`de los placeres del pecado por un tiempo.`"
Sabiendo que estaban sufriendo por Su causa, tenían su confianza fija en solo Él,
y en Su fuerza se levantaron sobre todas sus pruebas.

"`Acerca de este tiempo,`" dice James Parnell: "`tenía unos quince años de edad;
y después Dios me llamó para que visitara a algunos Amigos en la parte norte de Inglaterra,
con los que me había unido en espíritu antes de ver sus rostros.`"
Probablemente fue durante esta visita al norte, que fue a ver a George Fox,
quien en 1653 estaba en la cárcel de Carlisle y en cuyo diario encontramos que declaró:
"`mientras yo estaba en la mazmorra de Carlisle, James Parnell,
un muchachito de unos dieciséis años, vino a verme y estaba convencido.`"
De este comentario de George Fox, parece que James Parnell no había tenido,
hasta este tiempo, ninguna interacción con los Amigos,
aunque las personas con quienes él se había asociado antes en la
adoración religiosa se habían acercado a algunos de sus principios.
Por lo que había pasado antes,
es evidente que James Parnell ya había experimentado una verdadera conversión de corazón,
había sido llevado a ver la formalidad de los sacerdotes,
y se había separado de la costumbre de la adoración, para esperar solo en el Señor;
de modo que por esta entrevista con George Fox,
él estaba simplemente convencido de que la Verdad que Fox predicaba era
la misma a la que él mismo había sido guiado por el Espíritu de la Verdad.

George Fox tenía en este tiempo cerca de treinta y un años de edad,
y había estado ocupado durante unos siete años en predicar la Verdad.
Debe haber sido un consuelo indescriptible para él,
cuando fue encarcelado por motivo de la Verdad,
el haber recibido esta visita de un "`pequeño muchacho,`" para oír de él "`lo que el
Señor había hecho por su alma,`" y encontrar en su experiencia evidencia fresca de la
realidad sustancial de esos grandes principios que se habían abierto a su propia mente.
Y no menos reconfortante debe haber sido para James Parnell,
encontrarse con este padre en Israel,
y recibir una confirmación de su propia fe y una convicción más profunda de la Verdad,
por la conversación con tal anciano.
Es notable, sin embargo, que en ninguna parte menciona el nombre de George Fox.
No se sabe cuánto tiempo James Parnell estuvo con él,
pero encontramos que lo menciona en su compañía en Drayton,
donde tuvo una disputa con Nathaniel Stephens y con otros sacerdotes, en 1654.

James Parnell volvió a casa desde el norte,
y por un tiempo prosiguió su vocación externa,
y fue favorecido al experimentar la obra del Señor
progresando en él y Su Verdad manifestada a su alma,
cada vez más plenamente.
Manteniéndose fiel a la medida de luz impartida a él, por la fuerza de la gracia divina,
pronto fue llamado a proclamar la Verdad a los demás. George Fox dice:
"`El Señor rápidamente lo convirtió en un poderoso ministro de la Palabra de vida,
y muchos se volvieron a Cristo por él, aunque no vivió mucho tiempo.`"
Al principio, no fue enviado lejos de su hogar al servicio de la Verdad;
y mientras ocasionalmente se dedicaba a la obra del Señor,
todavía estaba preocupado por llenar el tiempo intermedio
con atención diligente a su llamado exterior.
Entre los diecisiete y dieciocho años, probablemente hacia mediados de 1654,
fue enviado a un pueblo a unos quince kilómetros de distancia,
en donde el Señor estaba dando a conocer Su Verdad.
Él no sabía, cuando salió de su casa, que tendría que ir más allá de ese lugar,
pero estando allí, él fue movido a ir a Cambridge, y a partir de entonces,
aparentemente estuvo exclusivamente ocupado en el servicio del Señor,
ya fuera predicando, escribiendo epístolas para confirmar a los que estaban convencidos,
o libros contra los opositores de la Verdad,
o estando en prisión por su testimonio y fidelidad a la causa de Cristo.

Él fue a Cambridge sin saber qué hacer allí, ni qué podía hacer,
y sin conocer a nadie en ese lugar que lo recibiera en su casa.
Había oído que el Alcalde de Cambridge había azotado a dos Amigos por declarar la Verdad,
al pasar por la ciudad, y no sabiendo que le esperaba una porción similar,
en obediencia a lo que él entendió ser su deber, y sin conferenciar con carne o sangre,
o siendo intimidado por el rumor de la persecución que otros habían experimentado,
siguió fielmente su viaje, y fue consolado por la presencia y la dirección del Señor.

Habiendo llegado a Cambridge, fue recibido con gusto por algunos,
y se enteró de que había un Amigo en prisión por declarar el mismo testimonio,
con el cual él mismo fue comisionado.
Sin embargo, esto no le impidió escribir en dos semanas dos documentos,
uno "`contra la corrupción de los magistrados`" y el otro "`contra la corrupción de
los sacerdotes,`" por los cuales él fue entregado por William Pickering el alcalde,
a prisión. La fecha de su encarcelamiento se puede ver en la siguiente
observación en esta carta de Richard Hubberthorn a Francis Howgill,
fechada el 4 del séptimo (noveno) mes de 1654:
"`James Parnell y yo todavía estamos en el calabozo,
donde nos pusieron el 28 de este último mes; pero sentimos el poder de Dios,
y estamos en gozo y paz en el Señor; a Él sea la alabanza eterna por siempre.`"
James Parnell podría haber escapado de este encarcelamiento,
si hubiera estado dispuesto a "`dar una señal de
buena conducta;`" y en referencia a esto,
él dijo: "`Yo fui redimido de la generación que es culpable de fechoría,
y fui atado a un buen comportamiento por un vínculo
más fuerte que lo que el hombre puede hacer.`"
Fue detenido en prisión, en Cambridge, y por espacio de dos audiencias,
durante las cuales sus enemigos no pudieron acusarlo de violar ninguna ley.
En la segunda audiencia se convocó un jurado y se intentó probar
los documentos que había publicado como "`escandalosos y sediciosos.`"

Los miembros del jurado parecen haber poseído un espíritu
más independiente de lo que era común en aquellos días,
cuando algunos pocos individuos tenían a menudo el
poder de manipularlos como ellos quisieran,
para actuar contra todo lo relacionado con nuestro sentido de lo que es
debido a nuestros compañeros y las leyes establecidas de la comunidad.
Ellos dieron su veredicto: "`que no encontraron nada,
sino que los documentos eran suyos.`"
Sus enemigos estaban enojados porque sus intenciones eran obtener una forma legal,
bajo la cual podían seguir persiguiéndolo;
y aunque lo habían detenido injustamente en el confinamiento por tanto tiempo,
no lo liberaron inmediatamente, sino que lo mantuvieron en prisión durante tres días más;
y luego lo enviaron fuera de la ciudad con una escolta
de hombres que llevaban armas y varas,
y con un pase bajo el nombre de "`un pillo.`"
Pero al día siguiente, un juez de paz,
procedente de Cambridge y sabiendo que él era inocente,
"`atestiguó que el pase era falso,
y lo devolvió.`" Así James Parnell fue puesto en libertad.
Pero, a pesar del rudo trato que había experimentado durante su primera visita,
pronto creyó que se requería que él volviera a Cambridge.
Allí, en los las partes cercanas, proclamó abierta y libremente la Verdad por medio
año. Muchos recibieron con alegría su mensaje;
aunque él dice que "`había más adversarios,
pero la Verdad se extendió y conquistó a sus enemigos.`"

James Parnell,
siendo joven en años y de "`poca estatura y humilde en su presencia y apariencia
externa,`" fue denominado "`el niño tembloroso`" por los "`profesantes envidiosos,`"
contra cuya formalidad y seguridad carnal estaba comprometido a declarar.
Samuel Cater había sido un anciano entre los Bautistas,
pero después de haber sido convencido de la Verdad
a través del ministerio de James Parnell,
se encariñó profundamente con él, y se mantuvo con él tanto como le fue posible.
Así tuvo la oportunidad de familiarizarse íntimamente con él,
no sólo en cuanto a su doctrina y ministerio público,
sino también en cuanto a su carácter privado.
Él nos informa que, a pesar de su juventud y apariencia poco impresionante,
estaba notablemente dotado de sabiduría divina,
y "`en el nombre y en el poder del Dios viviente,`"
le fue permitido "`tapar la boca de aquellos,
que surgieron en la fuerza del poder de las tinieblas para oponerse a la Verdad de Dios,
para atraparlos en sus propias trampas y confundirlos
ante los ojos de todos los que tenían ojos para ver.`"
Él tenía "`un buen don para declarar la Verdad,`" estaba lleno de celo
y coraje celestial al dar un testimonio sin lisonjas a todos,
y estaba eminentemente calificado para todos los servicios a los que se le llamaba,
estando capacitado para administrar correctamente la palabra,
tanto dando instrucciones a las mentes honestas que estaban buscando,
como identificando y evidenciando a los engañadores.
Él llamó a la gente al arrepentimiento y a volverse a la
luz del Espíritu de la Verdad que visitaba sus corazones,
para que por el poder de Jesucristo pudieran experimentar sus almas renovadas,
sus vidas santificadas y sus corazones traídos a la paz con Dios.
Los exhortó a apartarse de las enseñanzas de los hombres carnales,
y de su confianza en el brazo y sabiduría de la carne,
para apoyarse en la fuerza y depender solo de las enseñanzas de Jesucristo,
para aprender en Su Luz sus propias condiciones y
el camino a una comprensión eficaz de Él,
como su Salvador.
Y cuando alguno se volvía a la Verdad, él era muy serio en sus exhortaciones,
para que tuviera cuidado de caminar en la Verdad a la cual se había vuelto,
velando por ella, caminando en el temor de Dios y negándose a sí mismo;
llevando la cruz cotidiana y siendo fiel a esa pequeña
medida de luz y verdad que ya había recibido,
para que así pudiera conocer más.

Pero el joven James Parnell no sólo proclamó buenas doctrinas,
sino que también fue un buen ejemplo, y modelo de vida y conducta con los que predicó la Verdad,
así como con palabras.
Era serio, humilde, irreprensible en su conversación y sin manchas del mundo;
paciente y manso bajo los sufrimientos que soportó por causa de Cristo;
diligente y dispuesto en el servicio del Señor, aun en peligro de su vida.
Así, su presencia era una fortaleza y consuelo para los rectos,
pero un temor y terror para aquellos que no caminaban
correspondiendo a la profesión que hicieron.
"`Era un hombre inocente y vivía en los testimonios y en el temor
de Dios`"--señaló Thomas Bayles--"`no buscó nada para sí mismo,
sino solo se esmeró para que el pueblo pudiera ser
llevado al conocimiento y al amor de Dios.`"

El lector estará interesado en el siguiente tratado,
seleccionado de las obras de James Parnell;
parece haber sido la primera de sus publicaciones.
Fue escrita en 1654, cuando tenía diecisiete años de edad.
Se titula:

[.embedded-content-document.paper]
--

[.blurb]
=== Una prueba de la Fe: donde se descubre el fundamento de la fe de los hipócritas, que perece; y de la Fe de los Santos, fundada sobre la Roca Eterna; para que todos vean cuál es su fe y en qué confían.

¡Vengan!
Prueben su fe, todos ustedes profesantes de la piedad, de Dios y de Cristo,
que dicen que Dios es su Padre,
y Cristo su Redentor y que creen en Dios y que son salvos por medio de la fe en Cristo.
¡Vengan!
Examinen el fundamento y cimiento sobre los cuales su fe está fundada,
porque la fe y la esperanza del hipócrita perecen,
(Job 8:13) las cuales están en palabras y sobre un fundamento débil.

Ustedes dicen, que son salvados por la sangre de Cristo y por Sus llagas son sanados;
y entonces Lo hicieron el fundamento de su fe.
¿Pero de qué han sido salvados?
¿Y de qué son sanados?
Busquen adentro y vean.
Cristo vino para salvar y redimir a los pecadores de sus pecados,
y a sanarlos de su herida, para herir la cabeza de la serpiente,
para atar al hombre fuerte y lanzarlo fuera de Su casa;
y para abrir las puertas de la prisión,
para poner en libertad a los encarcelados y para llevar cautiva la cautividad;
para lanzar al anticristo fuera del templo de Dios,
que se sienta allí como Dios y dice que es Dios.
Y Cristo vino a desgarrar ese velo de tinieblas, a abrir los ojos de los ciegos,
a destapar los oídos sordos,
a hacer ciegos a los que pueden ver y a hacer sordos a los que pueden oír;
para darles fuerza a los débiles y para debilitar a los fuertes;
para alimentar a los hambrientos, y para hacer morir de hambre a los que se alimentan;
para hacer una separación entre lo precioso y lo vil, entre el trigo y la cizaña,
entre las ovejas y las cabras; y para comprar para el hombre,
lo que el hombre ha perdido.
Para este fin Él ha venido.
Y los que pueden ser testigos de esta obra,
pueden testificar de Él y pueden reclamar una herencia en Él,
y tener la seguridad de su salvación. Su fe se levantará contra la bestia, y vencerá;
porque el Cordero obtendrá la victoria.
Pero los que no pueden testificar esto, no pueden ser testigos de Cristo,
y son los reprobados en cuanto a la fe.

Ahora, aquí todos ustedes borrachos son excluidos;
aquí todos los que juran son excluidos; aquí todos los orgullosos,
codiciosos y lujuriosos son excluidos; aquí todos ustedes burladores, escarnecedores,
murmuradores, maldicientes, estafadores, envidiosos,
jugadores y deportistas son excluidos.
Y todos ustedes fariseos, profesantes de la cristiandad,
que viven en las modas y costumbres del mundo,
deleitándose en los placeres y vanidades del mundo, y tienen comunión con él,
cuya ciudadanía está entre los hijos del mundo, son excluidos.
Ustedes que limpian sólo el exterior de la copa,
mientras que el interior está lleno de lujuria e inmundicia, de orgullo, de avaricia,
y de toda suciedad; ustedes son paredes blanqueadas y sepulcros pintados,
que engañan el ojo y el oído carnal,
pero el Señor examina el corazón. Todos ustedes son excluidos de la fe verdadera,
la cual "`purifica el corazón`" (Hechos 15: 9). La serpiente es la cabeza en ustedes,
y el hombre fuerte guarda la casa, y uno más fuerte que él, aún no ha llegado;
pero el anticristo se sienta en el reino, y reina como un "`ángel de luz.`"
De hecho, la herida del pecado está todavía fresca;
el velo de las tinieblas está puesto sobre ustedes, y la muerte reina.

¡Ay!
Cristo reposa en un pequeño pesebre,
y la posada de sus corazones está ocupada por otros invitados.
Y aquí, ustedes no puede reclamar la sangre de Cristo;
no tienen nada que hacer sino hablar de Dios y de Cristo,
y tampoco tienen seguridad de su salvación. Su fe es vana y vana su esperanza;
su fundamento es de arena y no soportará en el día del juicio,
sino será como una caña rota en que apoyarse.
Aquí todas sus oraciones y alabanzas, cantos, oraciones, bautismos y sacramentos,
sobre los cuales edifican su fe, y piensan que obtienen méritos de Dios, todo es en vano,
al ser ofrecido desde un corazón inmundo.
¿Cómo pueden estar limpios sus corazones mientras ustedes viven en pecado?
Porque el pecado reside en sus corazones, y mientras el pecado esté allí,
la pureza no puede permanecer allí; nada que sea puro puede salir de una vasija impura;
Dios no pone su tesoro en una vasija inmunda; Él es puro y no recibe nada que sea impuro.

Aquí toda su fe se muestra vana;
porque destruyen su fe con las palabras de su propia boca,
que dicen que creen que jamás vencerán el pecado mientras estén en este mundo,
y que jamás serán libres del pecado.
Y aquí demuestran que su fe no está edificada sobre Cristo,
que vino a destruir las obras del diablo y a limpiar de todo pecado.
Pero aquellos cuya fe fue edificada sobre Él, testificaron esto y dijeron:
"`La sangre de Cristo nos ha limpiado de todo pecado,`" y "`los que son de Cristo
han crucificado la carne con sus pasiones y deseos,`" que son la base del pecado,
y "`el que cree es nacido de Dios;
y el que es nacido de Dios no puede cometer pecado,`" etc.
Así que ahora,
¿qué verdadera seguridad tienen de su salvación? ¿O sobre qué está su fe edificada,
cuando tanto Cristo como las Escrituras testifican contra ustedes?
La fe, que no está edificada sobre la Roca, Cristo Jesús, es vana, y perece;
y aquellos que tienen la verdadera esperanza en él, "`se purifican a sí mismos,
así como Él es puro.`"
Aquí su fe es buscada, tratada y probada, y se encuentra vana y perecedera,
y por tanto no es la fe que se basa sobre la Roca que no perece.

Por lo tanto, ¡bajen, todos ustedes fariseos altivos!
Dejen de lado todas sus profesiones; echen por tierra todo su viejo edificio,
y comiencen y pongan un nuevo fundamento.
Cuanto más alto sube el fariseo,
mayor será su caída. El que quiere ser sabio primero debe convertirse en un necio,
porque el hombre por su propia sabiduría no conoce a Dios.
Por lo tanto, el fariseo, que está en su propia sabiduría,
está excluido del conocimiento salvador de Dios.

Y todos ustedes que voluntariamente son criaturas ciegas, carnales e ignorantes,
de quienes mi alma se compadece, cuando veo cuán ignorantentemente son conducidos,
que ponen su fe en sus antepasados, y viven en la ligereza y el descuido,
gastando su juventud en la vanidad, en los juegos, en el placer y en los deportes;
en embriaguez, jurando y mintiendo; en vanas conversaciones y burlas necias; en orgullo,
lujuria e inmundicia; y dicen que siguen a sus antepasados;
y que sus placeres son meros "`pasatiempos y recreación,`" y su
vana conversación y burla tonta es sólo "`pasatiempo y alegría.`"
Así que ustedes desperdician su tiempo y dicen que la bebida,
el desenfreno y la fiesta,
son "`disfrutar buenas compañías y ser buenos vecinos;`" así cubren sus pecados e iniquidades.

Mas, ¡ay de aquellos que esconden su pecado y cubren su iniquidad!
Todo esto no les servirá de nada,
ni sus antepasados pueden excusarlos delante del Señor.
Porque en el principio Eva no pudo justificar a Adán,
ni excusarlo;
sino que él fue condenado porque oyó la voz de ella y desobedeció
al Señor. Así Adán sufrió por su propio pecado,
y también Eva por el suyo.
Y así no habrá ninguna excusa para ustedes en el día de rendir cuentas, al decir:
que siguieron a sus antepasados, e hicieron como ellos hicieron antes de ustedes,
porque entonces el Señor dirá: "`Como siguieron las tradiciones y modas,
las costumbres e invenciones de los hombres, y han escuchado la voz de la serpiente,
y han desobedecido Mi voz y mandamiento, y han despreciado Mi consejo,
y no han deseado Mi reprensión, sino echaron Mi ley a sus espaldas,
y pisotearon Mi misericordia bajo los pies, y han convertido Mi gracia en libertinaje,
y han gastado mi creación en sus concupiscencias; y apedreado, acorralado, abofeteado,
encarcelado y tratado vergonzosamente a Mi mensajero,
el cual les envié para prevenirlos de su iniquidad,
y han crucificado a mi Hijo en sus corazones--por tanto, apártense de mí,
hacedores de iniquidad, (¡No los conozco!) al tormento eterno,
preparado para el diablo y sus ángeles.`"
Miren ahora cuán vana es su esperanza, y cuán débil es su fe,
cuando tienen más segura su condenación que su salvación. Porque
el Señor dice que ninguna persona injusta puede entrar en Su reino,
ni ningún corrupto ni cosa inmunda.

Por lo tanto, todos ustedes que desean la salvación de sus almas,
traten y prueben su fe y esperanza en las que confían;
y tengan cuidado de confiar en una caña rota,
para que no los engañe. La experiencia les ha enseñado que
si el fundamento de un edificio está deteriorado e inútil,
el edificio caerá cuando venga una tormenta.
"`Así que, el que piensa estar firme, mire que no caiga.`"
Y todos ustedes, cuyo deseo es caminar en pos de la justicia,
escuchen a ese Testigo en sus conciencias, quien levanta deseos tras la Justicia,
y quien les muestra la vanidad de sus vidas, quien los frena cuando hacen lo malo,
y los molesta y atormenta en su conciencia cuando han hecho cualquier
mala acción. Estén dispuestos a ser guiados por este Testigo,
y los llevará al arrepentimiento y a la novedad de vida;
y a abandonar aquellas cosas que Él descubre que son contrarias a la voluntad de Dios.
Y si ustedes están dispuestos a seguir a este Testigo y ser guiados por Él,
encontrarán un Maestro continuamente presente,
examinándolos en sus conciencias por pensamientos vanos, frívolos y ociosos,
y palabras y acciones innecesarias;
y también crucificará la concupiscencia que es el fundamento de estas cosas.
Esto los llevará fuera de los caminos de la muerte, al camino de la vida;
fuera de las tradiciones, costumbres, modas y opiniones del mundo,
a la seguridad de la Verdad Eterna.

Y ustedes, que están dispuestos a seguir esta Luz y a ser guiados por ella,
no necesitarán a ningún hombre que les enseñe; porque Ella será un Maestro para ustedes,
enseñándoles y dirigiéndolos en justicia, pureza y santidad.
Y si ustedes son diligentes, manteniendo su mente en el interior,
con un oído abierto a la Voz pura,
la encontrarán presente dondequiera que estén--en los campos, en sus camas,
en los mercados, en la empresa,
o dondequiera que estén. Cuando su sacerdote o maestro externo esté ausente o lejos,
Ella estará presente con ustedes y los controlará
y condenará por lo que ningún ojo externo puede ver,
y limpiará sus corazones de lujuria, engaño e inmundicia,
y purificará sus corazones y hará un templo apto para que Aquel
Puro habite en él. Y entonces sus sacrificios serán puros,
porque vienen de un corazón puro y el Señor los aceptará.

Pero, si ustedes quieren alcanzar esto,
deben estar dispuestos a negar sus concupiscencias, vanidades,
placeres y cualquier cosa que haya sido su vida; porque Cristo ha declarado:
"`El que quiera salvar su vida, la perderá; y el que pierda su vida por causa de mí,
la hallará.`" Así que, no es posible obtener la vida, sino por medio de la muerte;
no es posible obtener la corona, excepto a través de la cruz.
Por tanto, deben negarse a sí mismos, tomar su cruz diariamente y seguir a Cristo,
si quieren ser Sus discípulos.
Deben entregarse totalmente a ser guiados por la voluntad de Dios,
para que todo lo que sea contrario a la voluntad de Dios sea crucificado
y abandonado sin importar lo cercano o querido que sea,
ya sean tierras o vida, esposa o hijos, amigos y conocidos, o todo el mundo,
y todos los placeres en el mundo.
Porque el Señor ha dicho: "`El que ama algo más que a mí, no es digno de mí.`"

Así,
que el Señor Dios Todopoderoso prospere todos los
tiernos deseos que se levantan hacia Él,
y alimenten a las almas hambrientas y sedientas, como Él ha prometido;
y levanten lo que es de Él (Su Semilla) en todos Sus hijos,
para que solo Él pueda ser glorificado, alabado y honrado, quien es digno,
y a quien le pertenece todo.

Y este es el deseo de su alma, quien es un siervo del Señor, quien es odiado,
injuriado y ridiculizado por el mundo, porque no tiene comunión con él,
ni con sus vanidades, sino más bien atestigua contra sus caminos, modas, tradiciones,
costumbres, compañerismo, palabras y adoración;
y ve que todos son una imitación formal y una invención de los hombres,
fuera del Pacto de Dios, y por lo tanto no puede sino negarlos;
y por esta causa él es odiado por todos, tanto sacerdotes como personas:
cuyo nombre según el mundo es,

[.signed-section-signature]
James Parnell.

--

Los siguientes extractos de sus obras,
nos permitirán formar alguna idea de su ministerio y de
su trato directo con los profesantes carnales del Cristianismo,
de los cuales se expresó así:

[.embedded-content-document.paper]
--

Mas, alabado sea el Todopoderoso,
que ha debilitado sus manos y ha hecho pedazos su fundamento
y ha hecho resplandecer Su luz de las tinieblas,
para que sean así manifiestas,
para que todo su pueblo que ama la luz más que las tinieblas,
vean cuán ignorantes y ciegamente han sido conducidos, como extraños del Padre de la luz,
tras vanas tradiciones, costumbres, formas, ordenanzas e imaginaciones de los hombres,
con una profesión vana y una fe fingida.
Ustedes se han agarrado de nociones, pero aún viven en sus pecados e iniquidades,
siguen vivos en la primera naturaleza, bajo el dominio de la muerte,
todavía son extraños del Dios de la vida, y de Cristo,
Salvador y Redentor de Su pueblo de sus pecados.
Por lo tanto, ustedes están bajo el poder de las tinieblas y del engaño del anticristo,
tanto los sacerdotes como el pueblo; porque "`será el pueblo como el sacerdote`" (Oseas
4:9) dice el profeta, y sus líderes los hacen errar por sus mentiras y su ligereza.

Y aunque ustedes están llenos de maestros,
todavía están perdidos por falta de conocimiento verdadero,
y todavía son llevados cautivos en sus pecados e iniquidades,
siguiendo a los que tienen la forma, pero niegan la vida y el poder,
que "`siempre están aprendiendo, pero nunca llegando al conocimiento de la Verdad.`"
Ustedes se diferencian de los paganos en nombre o profesión, juicio u opinión,
pero siguen vivos en la misma naturaleza, en la caída,
bajo la maldición y son hijos de desobediencia,
en quienes el príncipe de las tinieblas gobierna.
Ustedes necesitan una ley externa para mantenerlos en temor y temblor ante Dios,
igual a los que ustedes consideran paganos; pero los justos no necesitan una ley externa,
"`porque la ley fue añadida por causa de la transgresión.`" Y ustedes están peleando,
matándose y devorándose unos a otros,
como lo hacen aquellos a quienes ustedes llaman paganos; y ustedes son bebedores,
calumniadores y mentirosos como lo son ellos.
Ustedes son escarnecedores, burladores, injuriosos, murmuradores, orgullosos, codiciosos,
idólatras y opresores altivos, como son tanto los sacerdotes como el pueblo.
Ustedes son idólatras, como ellos lo son, comiendo y bebiendo, y levantándose para jugar;
y son envidiosos y maliciosos, demandando,
desgarrándose y demoliéndose unos a otros en pleitos, tanto sacerdotes como el pueblo,
destituyendo a otros para establecerse ustedes mismos.
Ustedes están engañándose y defraudándose unos a otros de las cosas de la tierra,
que no es suya; y son aquellos que persiguen, golpean y apedrean a los inocentes hijos,
siervos y mensajeros de Dios.
En verdad, ¿qué pecado hay entre aquellos a quienes consideran paganos,
que no esté entre ustedes y abunde?
Sí, los que ustedes llaman paganos, pueden condenarlos en mucho de sus prácticas.
¡Oh!
Avergüéncense y ruborícense ustedes, sacerdotes y maestros de Inglaterra,
al ver su ministerio y sus frutos tan abiertos ante ustedes.
Y así ustedes manifiestan ser los que se acercan al Señor con sus labios y bocas,
pero sus corazones están en la tierra, lejos de Él;
de lo contrario caminarían más rectamente.
"`Pero,`" dice el Señor, "`en vano me adoran,
enseñando por doctrina los mandamientos de los hombres.`"

Y estas cosas, tanto Cristo como Sus Apóstoles,
las juzgaron y condenaron como cosas que están fuera del nuevo pacto;
porque aquí no puede morar ninguna persona injusta; y aquí,
todas las guerras han terminado, y "`las espadas son forjadas en rejas de arado,
y las lanzas en hoces.`"
Aquí, en el nuevo pacto, no hay opresión, ni auto-exaltación, sino, el que desea ser más,
debe ser menos.
Sí, ellos están establecidos en justicia y lejos de la opresión,
y sólo el Señor es Maestro.
Aquí no hay necesidad de una ley externa, porque "`no hay condenación,
para los que no andan conforme a la carne, sino conforme al Espíritu.`"
Y aquí no hay acepción de personas, porque todos son miembros de un solo cuerpo,
del cual Cristo es la Cabeza y se sirven unos a otros en amor.
Aquí está el nuevo pacto y los hijos del nuevo pacto,
que son lavados y purificados por la Sangre del nuevo pacto;
pero ustedes son ajenos y extraños de este pacto,
ya que viven en meros conceptos y profesiones externas.

--

[.offset]
En la misma obra Parnell describe así la verdadera Iglesia:

[.embedded-content-document.paper]
--

Y con respecto a la Iglesia, ahora está siendo recogida y redimida,
no por la voluntad del hombre, ni por la sabiduría del hombre,
sino por la voluntad y el poder del Espíritu de Dios, que, según Su promesa,
Él ha derramado sobre Sus hijos e hijas ahora en estos últimos días. Y
por este Espíritu somos llevados en el poder del Todopoderoso,
a declarar Su poderosa Verdad que el Señor ha decretado
que prevalecerá sobre los corazones del pueblo,
que es una buena noticia de gran gozo para los que la reciben;
pero para los obstinados y duros de cerviz y rebeldes, es noticia de tristeza y miseria.

Y aunque los mensajeros del Evangelio son por algunos rechazados, injuriados,
reprochados, burlados y despreciados, puestos en el cepo, apedreados y encarcelados,
maltratados, calumniados y abusados, sin embargo, bendito sea el nombre del Señor,
hay algunos encontrados dignos,
que reciben con mucho gozo a los mensajeros del Evangelio.
Estos saben cuán hermosos son los pies de los que traen buenas nuevas,
para avivar al justo Testigo de Dios en su interior,
y levantar el espíritu muerto a la vida,
para que lo vivo llegue a conocer y a alabar al Señor.
De esta manera el Justo viene a reinar,
y el maligno es juzgado, y la mente se vuelve de las tinieblas a la luz.
Es a este Testigo de Dios en cada criatura,
que predicamos y por Él somos manifestados--tanto de donde
venimos como del testimonio que declaramos.

Pero no somos conocidos por aquellos que no lo reciben;
y por lo tanto somos considerados engañadores y fantasiosos, vagabundos,
inestables y cosas por el estilo.
Sin embargo, esto para nada nos sorprende); porque leemos,
"`El siervo no es mayor que su Señor, porque si han llamado Beelzebú al padre de la casa,
¿cuánto más a los de su casa?`"--y "`si lo hubieran conocido,
no habrían crucificado al Señor de la gloria.`"
Aun así, hay un Testigo en cada conciencia,
tanto en los que creen como en los que perecen,
ante quien despejamos nuestra consciencia de la sangre de todos.
De hecho, este Testigo responderá por nosotros en el poderoso día del juicio,
aunque será la condenación de todos los que lo han odiado.

Pero, a todos los que reciben esta luz divina, Él les da poder para ser hijos de Dios.
Aquellos que son persuadidos y guiados por el único Espíritu de Verdad,
que el mundo no puede recibir (es decir, el Consolador, de quien han oído que vendría),
están por Él separados del mundo y redimidos de los rudimentos
y contaminaciones que están en él--sus modas,
sus costumbres, sus palabras, sus formas, sus modales, su crianza, su comunión,
amor y amistad, su honor,
su gloria y su adoración. Así ellos se convierten en extraños al mundo,
por lo que son odiados del mundo, porque no son del mundo.
Verdaderamente hay enemistad entre las dos semillas,
pues mientras éstos eran de este mundo, el mundo los amaba,
pero ahora que están reunidos fuera del mundo y separados del mundo
y testifican contra él (tanto en sus palabras como en sus acciones),
de ahí, la enemistad se levanta en el mundo contra la Semilla justa en ellos.

Estos son aquellos sobre quienes el fin del mundo ha llegado,
y a quienes se les ha dado a conocer los misterios del reino;
pero al mundo se les da en parábolas.
Y estos son aquellos que vienen con un brazo fuerte
y con poder para trastornar el mundo entero,
a quienes el Señor ha reunido y está reuniendo fuera del mundo,
por Su propio Espíritu de verdad y amor, para andar en el camino de la verdad,
en la calzada de la santidad,
donde los redimidos del Señor andan y le sirven y adoran en Espíritu y en verdad.
Así, el Padre tales adoradores busca que Le adoren,
en quienes Él está haciendo Su propia obra,
incluso destruyendo la vieja creación para "`crear nuevos
cielos y una nueva tierra,`" donde mora la justicia.
Y estas son las nuevas criaturas, en quienes la nueva obra es experimentada,
en quienes el Padre ha manifestado a Su Hijo, para que Él pueda condenar el pecado,
atar al hombre fuerte, expulsarlo fuera de Su casa,
conquistar sus bienes y así "`destruir las obras
del diablo,`" y matar a ese hombre de pecado,
incluso a aquel hijo de perdición que es exaltado sobre todo lo que se llama Dios,
sentado en el templo de Dios, y diciendo que él es Dios.
Este es aquel por quien el mundo es engañado, quien es el dios de este mundo,
el príncipe de las tinieblas, que gobierna en todos los hijos de desobediencia.
Juan, hablando en la Luz, dice:
"`el mundo entero está bajo el maligno`" y así Cristo viene con una espada
para hacer guerra contra el maligno y arrojarlo a las tinieblas de afuera,
y así quitarle su reino y gobernar Él mismo en justicia.

Él es el Rey de los Santos, que ha venido para redimir a Sí mismo un pueblo puro,
para lavarlos y limpiarlos de sus pecados con Su sangre,
y así lavar toda la inmundicia de carne y espíritu.
Y este es el verdadero bautismo por el cual son recibidos en Su iglesia y fe;
y aquí está el efecto de la obra de Su sangre en el hombre.
De hecho, Él está y continuará manifestando Su poderoso poder para purificar,
limpiar y hacer al hombre un templo apto para Él morar.

Así, Emmanuel--"`Dios con nosotros`"--se manifiesta,
y los cuerpos de los santos son templos del Espíritu Santo.
Así la Palabra de vida y reconciliación es experimentada
al levantar el alma hacia la vida y reconciliarla con Dios.
Éstos son los engendrados y nacidos de nuevo de la Palabra inmortal,
la cual "`vive y permanece para siempre,`" y aquí está la familia de Dios,
la familia de la fe y la familia del amor, que habla lo que ha oído,
visto y saboreado de la buena Palabra de vida, que estaba en el principio.
Estos son los hijos de la luz, quienes son sacados de las formas,
juicios y opiniones de las tinieblas, hacia la vida y poder de la piedad,
para caminar en la luz de la vida,
en donde son reunidos y unidos por el único Espíritu de amor y Vida en un cuerpo,
del cual Cristo es la Cabeza.
Aquí está la verdadera Iglesia, que el Señor está reuniendo, lavando,
limpiando y purificando por Su Espíritu, para redimir a Sí mismo una novia pura,
sin mancha ni arruga, ni cosa semejante,
cuyas partes internas son lavadas y purificadas por la Palabra,
por la cual ellos son reconciliados en amor y unión, que brotan de la vida de Dios.
Y aquí está la Vid y las ramas, y la comunión de la Iglesia,
todas alimentándose de un solo Pan y bebiendo de una Copa.
Sí, esto es Cristo, la vida de los santos, y todos los bautizados en esta Iglesia,
participan de esta comunión. Estos son los que se
han negado a sí mismos y han llevado la cruz de Cristo,
por la cual son crucificados al mundo, y el mundo a ellos,
que están reunidos en un pacto de vida, donde todos son consiervos bajo un solo Maestro,
sirviéndose unos a otros en amor y mansedumbre.
He aquí la verdadera humildad forjada en el corazón,
el verdadero lavamiento de los pies sin hipocresía.

Y así es la iglesia de Cristo reunida por un solo Espíritu;
y por el mismo Espíritu es circuncidada y bautizada en una sola vida, luz y poder,
donde todos viven como miembros de un cuerpo, del cual Cristo es la Cabeza.
Aquí está la bendita unión y comunión en uno,
y aquí Dios es adorado "`en espíritu y en verdad.`"
Y como Cristo es espiritual, así es Su Iglesia, que es Su cuerpo,
y también Sus ordenanzas.
Aquí están los verdaderos cristianos, no aquellos que tienen una noción de estas cosas,
sino los que las experimentan y las poseen en la vida.
Los que creen, tienen al Testigo en sí mismos.
Los que creen, han pasado de muerte a vida;
y "`la vida que ahora viven es en la fe del Hijo de Dios.`"
Estas son las nuevas criaturas,
que están "`en Cristo Jesús,`" para quienes no hay condenación,
que caminan no según la carne, sino según el Espíritu.

Contra ellos no hay ley,
porque ellos han sido sacados de esa naturaleza a la cual se le añadió la ley;
y son liberados por "`la ley del Espíritu de vida,`" y "`hechos
partícipes de la naturaleza divina`" de Cristo,
y así son hechos cristianos.
Y ahora conocen el efecto de la obra de la sangre de Cristo en ellos,
y el fin de Su venida, y el beneficio de Su muerte,
quienes están muertos con Él y resucitados por la muerte de la cruz.
Sí,
estos son los que han escapado de las contaminaciones del mundo
por el conocimiento del Hijo de Dios en ellos--Cristo adentro,
la esperanza de gloria, y si no es así, ¡no hay esperanza de gloria!
Porque los que no lo han experimentado así, todavía están en la reprobación,
como dice el apóstol (2 Corintios 13:5). Y aquí está el Hijo en los santos,
y el Padre en el Hijo, y así todos son hechos perfectos en uno.
Y aquí está la verdadera Iglesia, donde hay un Maestro, un Señor, una fe, un bautismo,
una luz, una vida y un camino, un Pastor y un rebaño,
y un Sacerdote sobre la casa de Dios.
Aquí hay una esperanza, una lengua, una familia, un Dios y Padre de todos.

--

Esto fue escrito en 1655,
cuando James Parnell tenía entre diecisiete y dieciocho años de edad.

Mientras viajaba en la obra del ministerio,
a veces sostenía disputas públicas con los diferentes profesantes religiosos de la época,
quienes, aunque en circunstancias ordinarias eran enemigos encarnizados entre sí,
no obstante,
se unían ardiente y cordialmente para oponerse a esa adoración pura y espiritual,
a esa santidad de vida, y a esa verdadera experiencia religiosa,
que a James Parnell le fue dado proclamar.

El 30 del tercer mes de 1655,
mientras James Parnell "`declaraba libremente la Verdad de Dios,`" en una casa de Fenstanton,
en Huntingdonshire, varios Bautistas con su maestro, Richard Elligood,
entraron en la habitación. Después de un rato el maestro se levantó,
y se dirigió a James Parnell:

[.discourse-part]
"`Señor, con su permiso, hablaré algo de lo que usted ha dicho.`"

[.discourse-part]
James Parnell respondió: "`Aquí no hay necesidad de cumplidos.`"

[.discourse-part]
El maestro continuó: "`Usted ha dicho que Dios no considera ninguna forma,
y sin embargo usted usó la forma, y así usó aquello que Dios no ha considerado.`"

[.discourse-part]
Y al preguntarle qué forma había sido usada, el maestro respondió: "`La letra escrita.`"

[.discourse-part]
A lo que respondió James Parnell:
"`El que usa la letra escrita para hablar de ella sin la vida y el poder,
establece una forma y hace una forma.`"

[.small-break]
'''

Esta respuesta satisfizo a la gente, pero el maestro siguió discutiendo.
Así que James Parnell dijo: "`Una forma es: la semejanza de una cosa,
pero no la cosa misma; tales como los que tienen la semejanza de una iglesia,
con sus ancianos, pastores y maestros, pero no la Iglesia misma.
Y muchos imitan las Escrituras,
pero no viven en la vida de Aquel que habló las Escrituras y así carecen de vida y poder.
Estos son los formalistas que hacen formas y semejanzas para engañar a los sencillos,
así como el diablo puede tomar la forma de '`un ángel de luz`',
pero él no tiene la luz ni el poder mismo.
Y es él, quien aparece para gobernar en los formalistas y en los actores de hoy;
pero el Día del Señor lo saca a la luz y por lo tanto se enfurece.`"

En varias ocasiones, cuando James Parnell iba a Cambridge,
él oía que cuando estaba ausente,
los Bautistas tenían la intención de intentar una disputa con él.
Después de algunas dificultades preliminares para llegar a un acuerdo
mutuo sobre el modo y los reglamentos de la disputa,
el 20 del mes 4, 1655, fue fijada.
Cuando ellos llegaron al lugar provisto por los Bautistas,
no se les permitió reunirse allí. Entonces fueron
a la casa de uno de los Bautistas del grupo,
donde la mujer de la casa se comportó de una manera muy poco cristiana hacia los Amigos;
lo que hizo que James Parnell señalara que,
"`claramente no se había apartado de la vieja naturaleza,`" y era evidente
que no había obtenido ningún beneficio de su bautismo en agua.
James Parnell entonces se fue a la casa de un Amigo,
en medio de un gran grupo de estudiantes groseros y de gente,
a quienes él les declaró la Verdad.

Después de un tiempo, llegó un mensaje de que los Bautistas estaban en la casa de Shire,
en el patio del castillo,
y habían enviado por él. Aquí James Parnell encontró a un tal Doughty, un Bautista, y a Rix,
un Independiente; dos grandes enemigos entre sí en ocasiones ordinarias,
pero ahora unidos contra él. Después de todos los
problemas para determinar cómo debían reunirse,
y la dificultad para conseguir un lugar, solo una pregunta fue hecha,
y solo una respuesta fue dada por James Parnell la cual satisfizo a algunos,
pero no a todos.
Sin embargo,
James Parnell tuvo una oportunidad de hablar con la gente
y demostrarle que las acusaciones contra la Verdad,
y contra él mismo como su mensajero,
no tenían fundamento. Muchos estudiantes groseros estuvieron presentes en esta ocasión,
y habiendo conspirado juntos, tan pronto como James Parnell dejó el patio del castillo,
se reunieron alrededor de él y lo trataron muy vergonzosamente.

En el siguiente mes,
mientras varios del pueblo del Señor se encontraban juntos en el huerto de un amigo,
en Littleport, en la Isla de Ely, John Ray, con otros dos maestros,
vinieron a ellos para "`excomulgar`" a Samuel y a Ezekiel Cater,
quienes antiguamente habían sido ancianos entre los Bautistas, pero,
habiendo sido convencidos de la Verdad por el ministerio de James Parnell,
se habían unido a los Amigos.
John Ray,
"`habiendo estallado con muchas palabras alborotadoras`" se
disculpó por no permanecer para probar sus declaraciones,
diciendo: "`debo estar en la Casa del Campanario dentro de poco^
footnote:[Entendiendo que la verdadera iglesia es el cuerpo espiritual de Jesucristo,
los primeros Cuáqueros no quisieron usar el termino
"`iglesia`" para referirse a un edificio físico,
y en su lugar usaron el termino "`Casa del Campanario`" (Steeple-house en inglés).]
dentro de poco.`"
Cuando terminó su reunión, James Parnell pasó a la ciudad,
y habiendo sido informado que John Ray estaba criticando
contra la Verdad en la Casa del Campanario,
fue allí con algunos Amigos.
Cuando terminó el sermón,
James Parnell "`se levantó y reclamó el orden de la verdadera Iglesia de 1 Corintios 14:
26-30, donde todos podían hablar uno por uno,
"`y si algo le fuera revelado a otro que estuviera sentado, calle el primero.`"
John Ray se negó a permanecer y a defender sus declaraciones,
aunque muchos de su congregación deseaban detenerlo.
James Parnell se dirigió después a la gente en el cementerio.

+++[+++La conducta de James Parnell aquí es digna de notar.
Aunque John Ray había perturbado la reunión de Amigos ese mismo día,
Parnell esperó silenciosamente hasta que el servicio terminara, y, entonces,
reclamó el orden de la Verdadera Iglesia, como lo estableció el Apóstol.
Él manifestó una disposición similar para mantener el orden correcto en una ocasión,
recién mencionada, y se negó a hablar en la casa Shire,
hasta que el carcelero le dio permiso.
Otra instancia aparecerá en breve.]

Al día siguiente, este mismo Ray le dijo a un amigo que James Parnell había dicho que,
"`él era la cabeza de la verdadera Iglesia.`"
Esto lo llevó con varios Amigos a asistir a una reunión
que los Bautistas estaban celebrando en una casa,
donde encontraron a John Ray hablando con la gente.
Tan pronto como él vio a James Parnell, dejó de hablar, cerró su libro y le dijo:
"`Salga de la casa.`"
Parnell respondió: "`¿Está limitado tu espíritu?
¿Está tu espíritu atado?`"
Él le dijo nuevamente que se fuera; y le preguntó que por qué lo molestaba.
James Parnell les preguntó en qué los había molestado,
"`¿no estaba yo en silencio hasta que me hablaron?`"
Siendo una reunión abierta, aunque en una casa privada,
James Parnell no se consideró obligado a marcharse,
(aunque John Ray manifestó gran enojo,
y uno de los ancianos empujó varias veces a Parnell por el pecho con las
manos.) Habiéndole dicho a John Ray que se avergonzaba de su doctrina,
"`sacudió el polvo de sus pies para testimonio contra ellos, y así los dejó.`"

Aunque, a veces,
James Parnell se dirigía con severidad a aquellos
que él consideraba viviendo a gusto en sus pecados,
o engañándose a sí mismos y a otros con una profesión sin la posesión de la Verdad,
o actuando como falsos maestros que hacían errar al pueblo
al enseñar como doctrina las tradiciones de los hombres,
aún así,
se desprende claramente por los testimonios de aquellos que conocían su carácter privado,
que era manso, gentil, y paciente, y sus discursos (tanto a los que estaban convencidos,
como a los que estaban todavía en las tinieblas,) evidenciaban una mente amable y afectuosa.
Su único objetivo en el uso de la dureza,
era para despertar a los hombres a una consciencia de lo terrible
de su condición si permanecían en un estado de no arrepentimiento.
Él había "`conocido los terrores del Señor,`" y por lo tanto,
estaba seriamente preocupado por llamar a otros para que "`huyeran de la ira venidera.`"
Y como él también conocía los dulces consuelos de Jesucristo, estaba por eso,
eminentemente calificado para invitar a los verdaderamente sedientos del alma
a que vinieran y bebieran de la misma Fuente viva de refrescamiento espiritual.
Él era, sin duda,
"`un buen ministro del Evangelio,`" y dejó muchas marcas de su ministerio.
En aquel día,
se verificó notablemente que "`de la boca de los
niños y de los que maman perfeccionaste la alabanza`",
y "`lo necio del mundo escogió Dios, para avergonzar a los sabios.`"

Samuel Tuke observa en sus memorias de Stephen Crisp--"`La
Sociedad en los condados de Cambridge,
Essex, Suffolk y Norfolk, fue levantada por primera vez y llegó a ser muy numerosa,
principalmente a través de la labor de tres instrumentos, James Parnell,
William Caton y George Whitehead,
ninguno de los cuales había alcanzado la edad de veinte años.`"

La siguiente carta original de Parnell,
en la posesión de la Reunión por los Sufrimientos,
dirigida a Edward Burrough y a Francis Howgill, puede ser insertada en este lugar.
Está fechada el "`día 18 del mes 5.`" No cabe duda que fue escrita en 1655,
y presenta muchos puntos de interés:

[.embedded-content-document.letter]
--

[.salutation]
Queridos amigos y hermanos:

En el eterno e inmutable amor y vida del nuevo pacto,
estoy con ustedes y allí los saludo, donde somos uno, en nuestras medidas,
aunque diez mil--todos hijos de un Padre, hermanos y hermanas de una familia,
y herederos de la promesa, todos en la medida del don de gracia, que nos ha sido dada.
En esto abunda nuestro gozo, y se hace completa en unos con otros.
En la Luz del nuevo pacto ustedes pueden leerme, donde estoy presente con ustedes,
y los abrazo y los saludo, aunque ausente en cuerpo.
Porque todos somos engendrados por una sola Palabra Inmortal,
y así nacemos de nuevo y llevamos la imagen única de nuestro Padre,
para que por esto nos conozcamos unos a otros como hijos de un Padre,
y veamos y leamos y disfrutemos unos de otros en
este mismo pacto inmutable de amor y luz.
He aquí la bendita unión y comunión y relación y
libertad gloriosa de los hijos del nuevo pacto,
que están sellados en este pacto eterno de vida.
Y esta es la gran riqueza del amor de Dios que nos ha sido concedida,
para que seamos encontrados dignos de este supremo llamamiento.

Queridos hermanos, recibí la carta que me enviaron de Cambridge,
con el mismo amor que la enviaron,
y la reconocí como prueba de su cuidado y sabiduría. Poco después fui a la Isla de Ely,
y tuve reuniones en dicha ciudad, y fui a la Casa del Campanario,
pero la gente grosera no me permitió hablar.
Sin embargo, fui poderosamente preservado por el poder de Dios,
y tuve una gran reunión en la ciudad ese día,
y fui enviado con mucho poder a encadenar y atar
a los incrédulos y a levantar el Testigo en los corazones;
por lo tanto, muchos fueron convencidos.
La ciudad está muy endurecida contra la Verdad,
pero aún veo más trabajo que hacer en ella.
Hay buenas personas llegando de Littleport, a la Isla.
Me quedé allí un tiempo con ellos,
y solamente en esa ciudad hay unos sesenta que se reúnen.

Durante el primer día tuve una reunión en Soham,
como a tres millas del coronel de Russell.
Allí fui movido a ir a la Casa del Campanario,
y ahí estaba un sacerdote de Londres que se subió a la silla del Fariseo;
y él era un verdadero fariseo, porque estaba muy pintado.^
footnote:[Los cuáqueros usaban la palabra "`pintado`" en el mismo sentido que Cristo,
cuando habló de sepulcros pintados o blanqueados, "`que por fuera, a la verdad,
se muestran hermosos,
mas por dentro están llenos de huesos de muertos y de toda inmundicia.`"]
Se me permitió quedarme hasta que él terminó;
y entonces fui llevado en gran poder para hablarles a él y a la gente,
que los encadenó a todos.
Ellos eran un grupo grande y muy grosero,
pero el poder de Dios fue maravillosamente visto en mi protección, de tal manera que,
no creo que me dieran ni un solo golpe.

La multitud era grande, así que me lancé al patio y allí me dieron lugar para hablarles,
y fui movido a hacerlo con mucho poder,
y se quedaron inmóviles como corderos a mi alrededor.
Al fin llegó un tal Robert Hammond, llamado juez,
que había estado en la Casa del Campanario;
dijo que había una proclama de que todos los que perturbaran
a los ministros en el momento de su ejercicio público,
debían ser detenidos como perturbadores de la paz; así, si yo no me iba, dijo,
sería detenido.
Me sentí libre de irme de ese lugar, pero les dije a él y a la gente,
que yo iba a declarar la Verdad en la ciudad ese día. Y así, bajo estas condiciones,
fui liberado.
Tuve una gran reunión en la ciudad ese día,
y allí estuvieron presentes varias de las personas que pertenecían al grupo en Chippenham.
Aquellos que estaban allí recibieron la Verdad de buena gana y hubo mucha gente convencida.

La noticia de esta reunión llegó a los oídos de Hammond,
y despertó su espíritu contra la Verdad.
Los sacerdotes y él consultaron juntos contra mí, y a la mañana siguiente,
él envió una orden por mí y me recluyeron en la cárcel
de Cambridge por perturbar al sacerdote,
cuando antes me había liberado de ese cargo, en presencia de cien personas.
Así que esto fue durante el último segundo día, que me enviaron a Cambridge,
y allí me pusieron en un calabozo entre los ladrones.
Pero al día siguiente, el juez Blackeley envió su orden y me liberaron del cautiverio;
aunque yo estaba muy dispuesto a permanecer si esta hubiera sido
la voluntad del Señor. Pero en Su gran sabiduría Él lo ordenó,
según Su buena voluntad y placer, porque no se lo mencioné a Blackeley,
pero él lo hizo de su propia voluntad.

Al día siguiente fui a una reunión a seis millas de Cambridge,
donde me reuní con mis queridas hermanas, Ann Blakely y Dorothy Waugh.
Ellas permanecieron en estos lugares por un tiempo.
Mi repentina liberación y mi llegada a la región resultaron muy útiles,
porque los opositores estaban muy exaltados y se habían regocijado por mi encarcelamiento.
Es probable, si el Señor quiere, que vuelva pronto a esos lugares por donde fui detenido,
porque hay un pueblo allí que tiene que ser engendrado.
Pero los opositores, me doy cuenta,
están tramando juntos el meterme de nuevo en la cárcel,
porque el carcelero ha estado hablando con Blackeley al respecto,
y está preocupado porque me dejó ir sin fianza y ahora amenaza
con obtener otra orden contra mí. Pero estoy contento,
ya sea encarcelado o no.
He pensado permanecer aquí por un tiempo, por si tienen que escribir algo.

Salúdenme con cariño a mi querido hermano George Fox,
y a todo el resto de mis queridos hermanos,
hermanas y compañeros de la obra en la viña del Señor.
Salúdenme a todos mis queridos y tiernos corazones,
a quienes el Señor ha escogido de la gran ciudad, Sodoma,
para que lleven Su imagen y glorifiquen Su nombre y sean
como señales y prodigios en una generación adúltera.
Que el Señor Dios prospere e incremente Su gloriosa obra en ellos y entre ellos,
con brazo fuerte y poder para derrotar a sus enemigos delante de ellos.

[.signed-section-signature]
James Parnell.

[.signed-section-context-close]
Desde Cambridge, 18 del 5to mes.

[.postscript]
====

Me alegraré de oír de George, o de cualquiera de ustedes.

====

--

Parece conveniente insertar en este lugar el siguiente extracto,
que constituye la conclusión de una de las obras de James Parnell,
titulada "`Escudo de la Verdad,`" en la que menciona brevemente algunas
de las acusaciones presentadas contra los Amigos y la respuesta a ellas,
frecuentemente con notable claridad:

[.embedded-content-document.treatise]
--

Y ahora algo a todos ustedes, los de tierno corazón,
que están convencidos por la Luz de Dios en sus conciencias la cual las hace tiernas.
Por el bien de ustedes me he abierto libremente,
y por lo tanto deseo que dirijan sus mentes a la
Luz de Dios en sus corazones (a la cual hablo,
la cual es mi Testigo, y la cual los ha convencido), para que sea su verdadera guía,
que los conducirá a la conversión a la Vida,
y ustedes testificarán conmigo contra el mundo, para que mi trabajo no sea en vano.

No consideren los escándalos, ni las falsas acusaciones e informes,
porque todo esto es la recompensa que los justos siempre han recibido del mundo.
Cristo, nuestro Señor y Capitán, mostró el ejemplo, como está escrito,
"`los que viven piadosamente en Cristo Jesús deben sufrir
persecución,`" y "`los que se apartan de la iniquidad,
se hacen presa.`"
Aquello en ustedes que no puede soportar estas cosas no es de Dios.
Vuelvan, pues, sus mentes hacia adentro, a esa medida de luz que está en ustedes,
la cual es sin engaño, apacible, que puede soportar todo,
como lo hizo tanto en profetas y apóstoles como en todos los santos hombres de Dios.
Esto los llevó a través de un buen reporte y un mal reporte,
a través de persecución y muerte.
Y este es el camino a la vida, y el que entra debe entrar por este camino.
No teman, sino dispónganse a renunciar y a desprenderse de todo,
aunque sea cercano y querido, sí, aunque sea su amigo y sus predilectas posesiones:
"`Porque el que ama algo más que a Mí, no es digno de Mí,`" dice la preciosa Perla.
Y "`El que no abandona todo y Me sigue,
no es digno de Mí.`" "`Moisés tuvo como mayores riquezas
el sufrir aflicción con el pueblo de Dios,
que disfrutar de los placeres de la corte de Faraón por un tiempo.`"
Porque los placeres de este mundo, y las aflicciones de este mundo,
duran solamente un tiempo y luego pasan.
Todas las cosas visibles pasan, pero el gozo del justo perdura para siempre;
y si nuestras esperanzas estuvieran sólo en esta vida,
seríamos los hombres más miserables;
pero el que persevere hasta el fin tendrá una corona de gloria,
como Pablo lo experimentó.

Así que, "`no temáis manada pequeña,`" sino sean fieles, valientes y audaces,
"`porque es la buena voluntad de vuestro Padre daros el
reino,`" y cien veces más recibirán de lo que pierdan,
ya sean tierras o vida, esposa o hijos, o lo que sea.
La promesa es para los fieles,
y su gozo y progreso será en la destrucción de sus enemigos internos,
cuando el Señor ponga a sus enemigos por estrado de sus pies.
Pero esto es experimentado a través de la guerra,
y el que persevera hasta el fin de la guerra lo experimentará. Esto, en mi medida,
lo experimento; y sacando amor tierno de mi alma hacia sus almas lo declaro,
y deseo que todos ustedes puedan experimentarlo conmigo.
Porque el amor es caridad, y la Luz conduce a través de todo.
Así que descanso en mi morada, conocido por todos los que me pueden leer en el Espíritu.

[.signed-section-closing]
Adiós,

[.signed-section-signature]
James Parnell.

--

El siguiente artículo, escrito en 1655, se leerá con gran interés,
especialmente cuando consideramos la juventud del autor:

[.embedded-content-document.paper]
--

[.blurb]
=== Una palabra a todos los que todavía están en sus propias formas, acciones e imitaciones.

Ustedes están actuando en esa naturaleza que es "`enemistad
contra Dios,`" la cual "`no se sujeta a la ley de Dios,
ni tampoco puede.`"
Así que todas sus formas y acciones son en vano, porque no son de la vida,
sino de la muerte en lugar de la vida.
Pero hay una vida que viene de la muerte,
porque en la destrucción de la muerte se obtiene la vida.
Por lo tanto,
presten atención a la Luz del Señor Jesús en sus
conciencias (cuya Luz es Testigo de Dios),
a la que le hablo en todos ustedes,
que testifica para Dios contra los secretos de sus corazones y los reprende
en secreto por todas las acciones y hechos de las tinieblas.
De hecho,
esta Luz los examinará y los hará ver lo que ustedes han
verdaderamente experimentado de la obra de Dios en sus corazones,
a través de toda su larga y gran profesión de fe en Cristo,
estimándose a sí mismos santos en Cristo y miembros de Su iglesia.
Y en esta Luz verán si verdaderamente han experimentado
la remoción de la tierra de su lugar,
y la remoción de las montañas por el ojo de la fe, y el velo de las tinieblas rasgado.

¿No está todavía el primer hombre firme en ustedes?
¿No están en la primera imagen, donde la serpiente es la cabeza?
Porque mientras ustedes son extraños a la Luz, y sus espíritus se apartan de la Luz,
andan errantes y vagando por los caminos de las tinieblas,
y entonces son los hijos de las tinieblas,
en quienes el príncipe de las tinieblas gobierna--a saber,
la serpiente que es la cabeza en el hombre carnal.
Pero la promesa es: "`La simiente de la mujer herirá la cabeza de la serpiente.`"
Pero mientras están actuando en su propia voluntad y sabiduría,
la serpiente es su cabeza,
y todavía no han venido a experimentar el cumplimiento de esta primera promesa,
sino que están todavía en la caída, bajo el poder de las tinieblas,
en la desobediencia y extraños a la cruz.
Estos, que están en esa naturaleza, no tienen parte en Cristo.
Porque ninguno llega a tener un derecho en Cristo sino por la cruz;
porque todos los que son bautizados en Cristo son bautizados en Su muerte;
y los que están muertos con Él,
viven con él. Los que están en Cristo son nuevas criaturas; las cosas viejas pasaron,
y todas las cosas son hechas nuevas.
Pero los que no están en Cristo, están todavía en el viejo Adán, y así en la caída,
bajo la maldición y bajo el dominio de la muerte,
expulsados de la presencia de Dios en la tierra, donde la muerte reina sobre todos,
desde Adán hasta Moisés, independientemente de lo que profesan.

Por lo tanto, léanse ustedes a través de la luz que viene de Jesucristo,
y brilla en sus tenebrosos corazones,
por aquella que escudriña el corazón y prueba la mente, y manifiesta todos los secretos.
A todos los que tienen el deseo de encontrar el camino de la Verdad,
dirijo sus mentes a esa Luz, volviéndose de la oscuridad a la luz,
para que así puedan ver cómo han vagado y se han
dispersado en los muchos caminos de las tinieblas,
en la tierra de oscuridad, en el día nublado y oscuro, como ovejas sin pastor,
siendo llevados por la voz de extraños lejos del Pastor de sus almas.
Por lo tanto, no escuchen más a los que gritan, "`Mirad aquí está el Cristo, o,
mirad allí está,`" que buscan poner sus mentes en lo externo,
para buscar a un Cristo externo, y una redención externa, y una santificación externa,
y una justicia externa, y un Dios externo.
Pero vuelvan su mente hacia adentro; porque el reino se encuentra en lo interno,
si alguna vez lo encuentran.
Porque no hay Camino para llegar al conocimiento verídico de la verdad, o de Dios,
o de Cristo, sino por ese don de Dios interno;
porque "`lo que se conoce de Dios se manifiesta en el interior`" (Romanos 1:19).

El camino hacia Dios se encuentra dentro de ustedes por medio de la Luz,
que manifiesta y mata a la muerte.
"`El espíritu del hombre es la lámpara del Señor,`"
y la "`vida de Cristo es la luz de los hombres.`"
Vuélvanse en sus mentes a la luz del Señor Jesús, la cual, si la aman,
y traen sus obras a ella,
les permitirá ver las obras de las tinieblas y los caminos de la muerte.
Y también la luz escudriñará en sus corazones y manifestará sus partes internas,
y les permitirá que vean lo que han perdido.
Y según ustedes aman esta luz, y "`la retienen en sus mentes`" y son guiados por ella,
los sacará de todos los caminos torcidos y adversos de las tinieblas,
a la luz de la vida.
Así encontrarán y conocerán la voz del verdadero Pastor que ha venido a buscar
y a reunir a todas Sus ovejas dispersas entre las montañas y los valles,
y de las muchas formas y caminos torcidos, por donde han vagado y reunirlas en un rebaño,
en un solo camino, en un aprisco, donde Él solo será su Pastor.

Y a medida que ustedes aman la luz y la siguen,
verán cómo los guiará fuera de sus muchas formas y muchos caminos, a un camino.
Los llevará fuera de su propia sabiduría e imaginaciones,
en las que han estado construyendo a Babel, y los despojará de toda su propia justicia,
con la que han cubierto sus corazones engañosos; sí,
la luz pondrá sus engaños delante de ustedes, y los traerá a juicio.
Y si ustedes aman esta luz y la siguen y están dispuestos
a esperarla (fuera de sus propias voluntades,
sabiduría, imaginaciones, pensamientos carnales, razonamientos, consultas,
auto-realización e imitación),
los llevará a distinguir la voz del verdadero Pastor dentro de ustedes,
de la voz del extraño, y así conocerán lo precioso de lo vil.

El que dijo: "`Yo soy la Luz,`" dijo:
"`Yo soy el buen Pastor,`" y Él los llevará a conocer el camino y la puerta del redil
si ustedes no corren en sus propias voluntades y buscan subir por otra parte,
porque el Camino es solo uno.
El que dijo: "`Yo soy la Luz,`" dijo:
"`Yo soy el Camino,`" y "`Yo soy la Puerta del redil.`"
Así que si ustedes se apartan de la Luz y tropiezan con la Luz,
tropezarán con todo y caerán. Pero si aman la Luz y desean seguir la Luz,
los conducirá a través de todo a negarse a ustedes mismos, a tomar la Cruz,
y a pasar por la buena y la mala reputación, por la persecución y por la muerte;
y el camino no será doloroso, sino gozoso.
Y así irán en el camino, y entrarán por la puerta del redil,
en la comunión y en la vida y en el poder y en la fe de los santos,
donde todos viven en unidad en Uno--unidos por Uno en un cuerpo.
Aquí encontrarán el final de todas las peleas y argumentos, divisiones y disputas.
Por lo tanto, dijo el Apóstol, "`¿Dónde está el sabio?
¿Dónde está el disputador de este mundo?
¿No ha enloquecido Dios la sabiduría de este mundo?`"
"`Yo los llamo a salir de entre ellos, a separarse y a no tocar lo inmundo,
y Yo los recibiré, dice Jehová; y Yo seré para ustedes Padre,
y ustedes serán Mis hijos e hijas.`"

Ahora ustedes son llamados, y este es el día de su visitación;
porque la luz ha venido al mundo, y si gustan retenerla en sus mentes, felices son;
pero si no, por ella se quedarán sin excusa,
y los juzgará en el último día. Porque el que ama la luz no andará en tinieblas,
sino que tendrá la luz de la vida; mas el que hace el mal aborrece la luz,
y esta es su condenación. Ahora,
el camino es claro para todos los sencillos que tienen el deseo de encontrarlo.
Declarado por un amigo y testigo de la Verdad Eterna.

[.signed-section-signature]
James Parnell.

--

James Parnell,
habiendo trabajado diligentemente en Cambridgeshire y Huntingdonshire pasó a Essex,
probablemente hacia mediados del quinto mes, 1655.
Según Stephen Crisp--"`Los campos en aquella región estaban blancos para la cosecha,`"
porque había muchos cuyos espíritus habían andado con pesadez y cansancio por su camino,
bajo la carga del pecado,
y quienes habían buscado entre las diferentes profesiones y opiniones de la época,
el conocimiento de lo que podría aliviarlos de él,
hasta que se cansaron de buscar maneras de escapar.
"`En respuesta al clamor de Su propia semilla,`" el Señor envió a James
Parnell entre ellos para predicar la Palabra de vida y proclamar el año
aceptable del Señor. Habiendo predicado el Evangelio en muchos partes,
tales como Felstead, Stebbing, Witham, Coggeshall,
Halstead y otros lugares donde muchas almas hambrientas
recibieron con alegría la palabra de vida,
y habiendo plantado muchas buenas reuniones, y confirmado a los que creían,
él al final fue a Colchester, cerca del sexto mes.
Este era el lugar de nacimiento de Stephen Crisp,^
footnote:[Stephen Crisp se convirtió en un eminente ministro
en los primeros días de la Sociedad de los Amigos,
sirviendo por los siguientes treinta y cinco años,
en el poder y sabiduría del Espíritu por toda Inglaterra, Escocia, Holanda y Alemania.]
y donde él entonces residió, siendo llamado como predicador entre una gente separatista.

Stephen Crisp fue educado a la manera nacional de adoración. Él fue,
desde su juventud más temprana,
sensible a las visitas de la luz celestial (aunque
no sabía entonces de donde venía esa luz),
que tanto lo reprendía por el pecado,
y le causaba paz y gozo al brotar en su corazón cuando era obediente a su llamado.
Pero la mente carnal se levantaba y excusaba el pecado, y lo conducía a la transgresión,
bajo la carga que a menudo le hacía llorar amargamente.
El buscó varias maneras de escapar de la condenación;
pero mientras permanecía "`el siervo del pecado,`" la luz
de la Verdad lo perseguía con profundas convicciones,
y rompía su paz más rápido de lo que él podía construirla,
haciendo que sus propias obras (que eran como delantales de hojas de higuera con las
que intentaba cubrir su desnudez) aparecieran como trapos andrajosos y sucios.
Él dice que no vio más allá de su sus propias obras,
como un medio de traerle paz con Dios.
Él oyó hablar de Cristo y Salvador; pero en la angustia de la ignorancia espiritual,
todavía tenía que exclamar, "`¡Pero, oh, que yo lo conociera!`"

En aquellos días, Stephen Crisp prestó oído a muchas disputas religiosas,
corrió tras los mejores ministros y leyó sermones; pero todo fue en vano.
No podía encontrar descanso, porque todavía sentía el poder del pecado en él,
y deseaba de alguna manera vencerlo.
Él se aplicó a otros en su angustia,
tanto entre la iglesia nacional y profesantes separatistas; pero ninguno podía ayudarlo.
Entonces él continuó clamando:
"`¿Dónde está la fe que purifica el corazón y da la victoria?`"
La ignorancia predominante de la experiencia viva de la obra de la religión
entre los que estaban haciendo una gran profesión de la misma,
tuvo el efecto de alejarlo, por un tiempo, de la religión por completo,
para buscar alegría y consuelo en el mundo.
Pero la mano del Señor era demasiado pesada para él,
de modo que él pronto volvió a buscar algo más sustancial
en la religión. Bajo estos sentimientos,
Él se sometió al bautismo en agua, pero pronto tuvo que llorar,
porque esto también era una forma sin poder, y no hacía más que limpiar el exterior,
pero no le daba esa limpieza interior que le permitiría
"`dar testimonio de buena conciencia delante de Dios.`"
(1 Pedro 1:21)

Así, viendo que todavía le faltaba lo que antes le había faltado,
les dijo a los ancianos de la Iglesia Bautista, que:
"`Dios pronto anularía todas sus adoraciones y religiosidades,
que estaban en el exterior y en las cosas carnales,
y daría a conocer una adoración por encima de todas ellas,
que permanecería para siempre.`"
Él había oído hablar de los Cuáqueros, y deseaba ver a algunos de ellos,
pero su mente carnal razonaba mucho en contra de algunas de sus doctrinas,
especialmente la de ser libre del pecado,
a pesar de que era eso lo que había estado anhelando toda su vida.

Tenía unos veintisiete años cuando James Parnell entró en Colchester.
Cuando vio por primera vez al joven mensajero,
pensó que podía desafiarlo y empezó a cuestionarlo, y trató de hacerlo hablar.
Pero pronto descubrió que James Parnell tenía un espíritu diferente,
es decir un espíritu de buen juicio, que era superior a su razonamiento carnal.
Crisp se vio obligado a reconocer la sabiduría con que él hablaba;
y dijo a los que estaban cerca:
"`Todas nuestras varas de profesión cristiana deben morir y ser devoradas por la suya.`"
Al día siguiente, fue a una reunión designada por James Parnell,
y tan grande era la autoridad con la que predicaba,
que Stephen Crisp se vio obligado a reconocer y a confesar la verdad.

El reporte interesante e instructivo,
que Stephen Crisp da de su propia experiencia en asuntos religiosos,
previamente antes de su encuentro con James Parnell,
sus sentimientos al ver por primera vez a este muchachito saliendo contra los
"`Goliats`" que habían sido demasiado poderosos para sus años de más madurez,
y de mayor familiaridad con las armas de debate,
el desprecio interior que sentía cuando pensó resistirlo por medio
de la argumentación y su subsiguiente convencimiento de la Verdad,
nos dan una evidencia sorprendente del poder y de
la autoridad del ministerio de James Parnell.
Él era joven, muy pequeño en estatura y de mala apariencia; sin embargo,
la sabiduría del hombre fue humillada ante aquel Espíritu por el cual él hablaba,
y del cual él era instrumento.

La siguiente carta original de James Parnell,
obtenida de la Reunión Mensual de Colchester, fue dirigida a Stephen Crisp,
probablemente poco tiempo después de su convencimiento.
Esta carta no tiene fecha.

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

Esté firme y mantenga su mente en eso que le permite
ver que sus enemigos son los de su propia casa.
Su imaginación es un enemigo; su sabiduría es un enemigo;
lo que ha sido precioso para usted es ahora su mayor enemigo.
Por lo tanto, ahora debe sacrificar lo que ha llamado precioso, y entregarlo a muerte,
para que el Justo sea resucitado y la Semilla justa
surja para que reine en usted y sea su Cabeza.
De esta manera la cabeza de la serpiente será herida.
En su medida, usted llegará a entender esto,
mientras usted more bajo la Luz que manifiesta su condición;
"`porque la luz es lo que manifiesta todo.`"
(Efesios 5:13).

Deje que aquel ojo se mantenga abierto,
el cual el dios de este mundo ciega en los hijos del mundo.
Porque con este ojo, los hijos de luz pueden ver a su enemigo,
y así el tentador es conocido, resistido y negado.
Por lo tanto, con este ojo fije una constante vigilancia,
y no deje que el ojo del necio vague al exterior,
ya que lleva la mente errante hacia fuera tras los objetos visibles.
Más bien, permanezca en la guerra, no dándole lugar al enemigo o a sus ilusiones,
sino conténtese con convertirse en un necio,
para que todos los pensamientos egoístas puedan ser juzgados.
Así recibirá la sabiduría de Aquel que la da generosamente y sin reproche,
para discernir y conocer las maquinaciones del enemigo.
Pero sepa que es en la muerte mediante la cruz a su propia voluntad y mente apresurada,
que el don de Dios es recibido.
Por lo tanto, se dice: "`El que creyere, no se apresure.`"
(Isaías 28:16).

Por lo tanto, no se cansen del yugo de la cruz, porque en la fe se hace fácil,
y la impaciencia es crucificada, y la paciencia tiene su obra perfecta.
Así que esté quieto en la medida de la Luz que ejercita su mente hacia Dios.
No desee nada, sino que sus pensamientos sean juzgados, y que el poder de Dios obre,
para que Él sea visto como todo.
Y por este principio y nada más debe ser guiado y actuar,
manteniéndose bajo el poder de la cruz con respecto
a la parte carnal y negándose a sí mismo,
tanto en lo particular como en lo general.
Y no considere quien esté disgustado, siempre y cuando Dios esté complacido,
porque en esto no se da ocasión de ofender a nadie.
Y aunque hay enemistad en el mundo, sin embargo,
como esto lo lleva a caminar hacia Dios en fidelidad,
así también lo lleva a caminar hacia el hombre con una conciencia sin ofensa.
Así que mantenga su mente en la Luz, y no se apresure a saber nada más allá de su medida,
porque así fue como Eva perdió su paraíso. Más bien,
humíllese bajo la voluntad de Dios y espere Sus enseñanzas, para que Él sea su Cabeza,
y encontrará el camino de la paz y habitará en unidad con los fieles.
Y aunque usted es odiado por el mundo, sin embargo, en Dios tendrá paz y bienestar.

[.signed-section-signature]
James Parnell.

--

Unos diez años después,
Stephen Crisp fue llamado a escribir un testimonio
sobre la persona y ministerio de James Parnell;
lo cual él hizo en un espíritu que manifiesta,
que el recuerdo de este instrumento (por el que después de mucho
tiempo su alma vagabunda y cansada había sido convertida al camino
que conduce al establecimiento en la Verdad) era algo muy precioso.
Después de hablar de la gran obra que el Señor por Su propio
brazo de poder había hecho en aquellos días,
él continúa diciendo:

[.embedded-content-document.testimony]
--

Los bebés han sido Sus mensajeros, y los niños han sido Sus ministros,
quienes en inocencia han recibido la revelación de Su Santo Espíritu,
por el cual han sido reveladas las cosas profundas de Su ley y
de Su glorioso Evangelio de vida y salvación. Y entre estos bebés,
que llegaron a recibir el conocimiento de los misterios del reino de Dios,
por la obra de Su divino poder, fue este noble niño, James Parnell,
que era un vaso de honor en verdad, y poderoso en el poder y Espíritu de Emanuel,
derribando y desolando muchas fortalezas poderosas y torres de defensa en las
que el antiguo engañador se había fortalecido a sí mismo y a sus hijos.
Se podría hablar mucho de este joven,
y un gran testimonio vive en mi corazón de su bendita vida,
y del poder y sabiduría que abundaban en él.

[.signed-section-signature]
Stephen Crisp.

--

La diligencia con la que trabajó James Parnell,
y el ardiente deseo de la gente por oír la Verdad,
son sorprendentemente ejemplificadas en el relato de sus
servicios al día siguiente de su llegada a Colchester.
Allí fue un séptimo día; y el primer día predicó la Verdad a muchos miles de personas,
primero en su propio alojamiento,
luego en la Casa del Campanario después de que el sermón había concluido,
y luego en una gran reunión designada para ese propósito.
Después de esta reunión, disputó con el maestro de la ciudad y otro sacerdote,
y en todo eso "`la sabiduría,
el poder y la paciencia de Cristo aparecieron gloriosamente`" para
convencer a muchos que fueron testigos de la obra de ese día.

Durante la semana se dedicó diligentemente a "`predicar, orar, exhortar y amonestar,
convirtiendo las mentes de todo tipo de profesantes a la Luz de Jesús.`"
Muchos recibieron la Verdad que les fue declarada y encontraron por medio
de una experiencia viva y personal, la realidad y sustancia de esa religión
que hasta entonces habían conocido solo como un nombre.
Pero hubo otros que se apartaron de él, y se negaron a creer.
Con ellos él discutía diariamente,
"`con gran autoridad y en la evidencia y demostración
del Espíritu,`" tapando la boca de los adversarios,
y muchos más llegaron a ser alcanzados y convencidos de la Verdad.

El predominio de la Verdad entre la gente provocó la ira de muchos,
que "`crujían los dientes contra él`" y algunos trataron de compensar la deficiencia
de los argumentos de sus sacerdotes golpeando a James Parnell con sus puños y bastones.
Bajo las muchas afrentas que tuvo que sufrir,
"`su espíritu nunca fue visto altivo en calor o en cólera,
sino que era un patrón de mansedumbre y paciencia,`" calmado en
las disputas y sin resentimiento bajo la injuria de lesiones personales.
Un día, saliendo de la casa de Nicholas Steeple, en Colchester,
alguien lo golpeó con un gran bastón, diciendo con sarcasmo blasfemo: "`¡Vaya!
Tomen eso por amor a Jesucristo.`"
A lo que James Parnell simplemente respondió: "`Amigo,
lo tomo por el bien de Jesucristo.`"
Permaneció en Colchester, trabajando diligentemente y sufriendo por la Verdad,
cerca de diez días.

La promulgación de los verdaderos principios cristianos, a través de James Parnell,
entre gente que desde hacía mucho tiempo deseaba y esperaba
que surgiera un día más brillante sobre la Iglesia,
fue tan convincente que los sacerdotes y otros profesantes comenzaron a alarmarse.
A través de su mediación, y por su predicación,
muchos informes calumniosos se levantaron contra la Verdad y sus mensajeros.
Ellos se esforzaron todo lo que pudieron,
para que a los ojos de la gente ella pareciera repugnante.
Pero cuando James Parnell estuvo entre ellos, para responder a sus falsas acusaciones,
los sacerdotes se apartaron y no dieron apoyo público a sus afirmaciones,
y dejaron sus congregaciones;
y James Parnell tuvo así la oportunidad de proclamar aún
más las verdaderas doctrinas de los despreciados Cuáqueros,
sin duda de una manera mucho más eficaz de lo que habría sido,
si los predicadores hubieran permanecido discutiendo con él. Finalmente
los sacerdotes comenzaron a nombrar reuniones especiales para intentar
persuadir a la gente de que la Verdad era error y herejía;
y así provocando y perjudicando sus mentes,
para evitar que escucharan a los ministros Cuáqueros.
Y al mismo tiempo ellos buscaban su propia protección y la represión de sus oponentes,
requiriendo la ayuda de los poderes seculares.

James Parnell,
habiendo oído que una de estas reuniones fue designada
para llevarse a cabo en el gran Coggeshall,
el 12 del sétimo mes, el sacerdote anunció públicamente,
"`ayunar y orar contra los errores de la gente llamada los Cuáqueros,`"
él fue movido a estar presente en dicha reunión. Y,
aunque estaba persuadido de que su objetivo era atraparlo y hacerlo prisionero,
si fuera a Coggeshall para defender los principios que había predicado; aun así, él dijo:
"`Yo fui hecho dispuesto, no sólo a quedar prisionero,
sino también a sufrir por la Verdad pura y eterna, por la cual fui hecho testigo.`"
Él manifestó en esta y en otras ocasiones un notable deseo
de proceder con orden y dar la menor causa de ofensa posible,
siendo, como él dice, "`presionado en espíritu a ir entre ellos,
en el nombre y defensa de la Verdad de Dios.`"
El día de la reunión,
él dejó a sus Amigos (probablemente reunidos para la adoración) sin decirles a dónde iba.
Otro Amigo lo siguió hasta la puerta y le preguntó si podía acompañarlo.
James Parnell le dijo que usara su libertad, pero que deseaba ir solo.

Cuando él llegó a la Casa del Campanario, varios niños se habían reunido tras él,
pero les pidió que entraran primero, para no causar ningún disturbio.
Él entró de forma ordenada y permaneció en silencio mientras
el sacerdote injuriaba y reprochaba a los Cuáqueros.
Cuando había terminado y estaba yéndose de su asiento, James Parnell dijo:
"`Este es el orden de la verdadera Iglesia, que todos puedan hablar uno por uno;
y si algo le es revelado al que estuviere sentado que el primero
calle,`" y luego procedió a hablar en nombre de los Cuáqueros,
de quienes el sacerdote había maliciosamente e ignorantemente difamado.
Pero pronto fue interrumpido por los sacerdotes,
que explotaron con un montón de palabras y causaron así gran confusión. Al fin,
el que había predicado, le preguntó a James Parnell,
¿qué podía objetar contra él? A lo que James respondió:
"`En que él había injuriado a los Cuáqueros,
y dijo que ellos estaban fundamentados sobre una base arenosa;
pero él demostraría que su fundamento no era arenoso, y que él era un profeta falso.`"

A él entonces se le permitió vindicar "`el fundamento de los Cuáqueros--el pueblo verdadero;
no a todos los que se llamaban Cuáqueros`"--cuyo fundamento es Jesucristo,
la pequeña piedra cortada de la montaña sin manos,
sobre la cual la Iglesia verdadera fue construida,
y que despedazaría todo lo que estaba mezclado.
Algunos entonces lo acusaron de que él no reconocía ninguna iglesia.
Él respondió: "`Reconozco una iglesia: la Iglesia en Dios.`"
A lo que el sacerdote Willis, quien había predicado,
dijo que "`él no habla más que tonterías,`" y dio como
ejemplo la expresión que Parnell había usado:
"`la Iglesia en Dios.`"
Entonces, James Parnell sacó su Biblia y les mostró que esta era una expresión bíblica,^
footnote:[1 Tesalonicenses 1:1; 2 Tesalonicenses 1:1]
de modo que el sacerdote y sus compañeros quedaron avergonzados.
Después de otra disputa,
le ordenaron a James Parnell que se quitara el sombrero mientras el sacerdote oraba;
pero en lugar de hacerlo, Parnell salió de la Casa del Campanario.

Él fue seguido por un tal juez Wakering, y fue arrestado,
pero se le permitió entrar a la casa de un Amigo hasta que terminaron su adoración,
donde él le habló a la gente que se había reunido.
Siendo llevado más tarde ante los Jueces, fue enviado a la cárcel común de Colchester,
como culpable,
"`con muchas otras personas de su reunión,`" de "`entrar de forma
desenfrenada en la iglesia parroquial de Great Coggeshall,
de causar una asamblea ilegal en la calle,
y de utilizar discursos amenazadores e intimidadores,
tendiendo al rompimiento de la paz.`"
La orden judicial lleva la fecha,
"`12 de julio de 1655:`" y está firmada por Herbert Pellham, Thomas Cook,
Dyonysius Wakering y William Harlackinden.

Quedó bastante claro quiénes fueron los actores principales de esta persecución;
porque cuando fue presentado ante los Jueces, había seis o siete sacerdotes presentes;
cuatro de los cuales eran independientes que actuaban como párrocos.
Estos predicadores provenían de las diferentes partes de Essex,
donde James Parnell había predicado tan eficazmente el evangelio,
para el convencimiento de la gente,
y uno de ellos habló en público a los Jueces con el fin de animar
sus espíritus a la persecución. "`Así`" dice James Parnell,
"`las iglesias se reúnen contra Cristo y Su reino;
y ahora los lobos rapaces vestidos en piel de oveja aparecen; sí,
sus frutos los manifiestan.
Estos son los que se llaman judíos, pero no lo son,
sino la sinagoga de Satanás. Estos son los constructores que han rechazado y rechazan,
la preciosa Piedra, que se ha convertido en la Piedra Angular;
y ¡ay de aquellos sobre quien esta caiga!`"

A él se le mantuvo muy aislado en la cárcel y a ninguno
de sus amigos se le permitió verlo "`con paz y libertad.`"
Él ocupó el tiempo transcurrido hasta la sesión judicial,
escribiendo una respuesta a su orden judicial (en la que expone claramente sus falsedades),
que envió a los magistrados que lo encarcelaron con el fin de "`limpiar su conciencia.`"
Las sesiones de la corte iban a celebrarse en Chelmsford,
que está a veintidós millas de Colchester; a lo que se vio obligado a caminar,
siendo enganchado con seis criminales a una cadena.
Él fue aparejado con un sospechoso de asesinato y, con otros tres,
se vio obligado a permanecer en la cadena día y noche.
"`Así,`" comenta James Parnell,
"`fui conducido por el país como un "`hazmerreír`" de todo el mundo;
pero la Verdad fue predicada en todo esto, y prevaleció en los corazones del pueblo.
Así pude regocijarme en todo y triunfar sobre mis enemigos.`"

James Parnell, como si fuera el criminal principal,
fue llevado ante el Juez con los grilletes en la mano;
pero como algunos del pueblo clamaron contra esta crueldad, al día siguiente,
cuando lo llevaron otra vez, le quitaron los grilletes.
Se leyó una larga acusación que contenía los mismos cargos como la orden de la corte,
y cuando varios testigos dieron su testimonio en su contra,
la respuesta que él había escrito a los cargos y enviada a los jueces,
fue leída abiertamente en la corte.
El Juez Hills hizo todo lo que pudo,
por medio de una interpretación equivocada de los escritos de Parnell,
para enfurecer al jurado contra él, y hasta llegó a decirles que,
si no lo encontraban culpable, el pecado estaría sobre sus propias cabezas.
Pero él no permitía que James Parnell dijera ni una palabra en su propia defensa.
A pesar de esta injusta conducta,
el jurado regresó y dijo que solo podían acusarlo por el documento que había
escrito en respuesta a su orden judicial después de su encarcelamiento,
y que no podían encontrarlo culpable de los cargos en la acusación. Esto, sin embargo,
no satisfizo al Juez,
y finalmente logró sacar algunas palabras del presidente del jurado,
con las que el resto del jurado no consintió,
por medio de lo cual asumió un poder legal para volver a ingresar a Parnell a la prisión,
habiendo impuesto dos multas por el valor de unas cuarenta libras --una por "`desprecio
del ministerio,`" y otra por "`desprecio de la magistratura,`" diciendo que el
Señor Protector (Oliver Cromwell) le había encargado castigar a cualquiera de
esas personas que mostrara desprecio a la magistratura o al ministerio.

Tales eran los procedimientos inconstitucionales de sus enemigos contra él,
que a algunos de sus acusadores se les permitió estar de pie sobre el estrado,
cerca del Juez, y con frecuencia susurraban en su oído durante el juicio.
Pero, él dice, "`como el engaño de mis enemigos se manifestó a muchos,
e hizo que esos muchos confesaran la Verdad en sus corazones,
me regocijé en todo y mis sufrimientos no fueron dolorosos, sino de gozo.`"
Al no sentir libertad de pagar las multas injustas que se le habían impuesto,
él fue puesto en prisión. El Juez le había dado un cargo especial al carcelero,
de no permitir que los lunáticos (con lo que se refería a los Amigos) se acercaran a él.

En esta ocasión James Parnell declaró:
"`Entonces ellos me trajeron de regreso a la prisión,
donde todavía permanezco en la paz y en la libertad de mi espíritu,
que nadie puede quitar, aunque mi cuerpo esté en las manos de mis enemigos.
Sin embargo sé, que el Dios invisible está obrando en secreto por Su poder,
y con brazo fuerte está llevando a cabo esta gran
obra la cual Él ha empezado en la tierra.
Sí, Él derribará y anulará todo, hasta que todo quede en Su mano,
a quien esto le pertenece.
Y Él exaltará Su reino en el corazón de Su pueblo, y Su Hijo regirá sobre la tierra.
Todos Sus enemigos serán Su estrado, y se inclinarán ante Él,
y echarán sus coronas ante Él, y reconocerán Su poder.
Sí, Él destruirá todas las formas sin vida, las falsas semejanzas e imágenes,
que han sido levantadas por hombres en sus propias imaginaciones, y llamadas iglesias.
Él las destruirá en pedazos, y los poderes de la tierra, unos contra otros,
como una vasija de alfarero.
Aunque ellos ahora desprecian la Piedra Angular, con todo ella los hará polvo.
"`Porque nuestro Dios es fuego consumidor;`" y ¿quién
es capaz de estar de pie en el Día de Su ira?
Horrenda cosa es caer en manos del Dios vivo.
Por tanto ¡ay! de todos Sus enemigos y del que levanta su mano en contra de Su Creador,
para hacer lo contrario a lo que Él ha decretado.`"

Después de la sesión de la corte, James Parnell creyó oportuno enviar una carta al Juez,
en la cual,
después de quejarse del prejuicio e injusticia que él le había manifestado a él, dice:
"`¿Considere qué ventaja tendrá usted cuando tenga que dar
cuenta delante del Señor Dios de los cielos y de la tierra,
el Juez de todos los vivos y los muertos,
si usted ahora tiene poder para mantener este cuerpo en prisión, o tomar mi vida,
la cual estoy dispuesto a rendir libremente en vez de negar la Verdad de Dios?
Y si yo pagara un centavo por la libertad de mi cuerpo en esta causa,
esto sería como si pagara toda la multa que usted injustamente ha puesto sobre mí;
porque al hacerlo, me reconocería transgresor cuando no soy culpable.
Y, además, una libertad comprada sería una esclavitud para mi espíritu,
pero la libertad que tengo, aun bajo sus cadenas, es una esclavitud para usted;
y esta libertad que siento, usted no puede robármela, aunque haga lo que haga;
porque es don gratuito de Dios.`"

En el Castillo de Colchester,
James Parnell tuvo que padecer una serie de crueles persecuciones,
de una magnitud y carácter tal vez escasamente superados.
El carcelero llevaba a cabo rígidamente las instrucciones del Juez,
no permitiendo que sus amigos llegaran a verlo,
hasta donde convenía a su propio beneficio o capricho.
La juventud de James Parnell, su carácter como ministro viviente del Evangelio,
su perseverante diligencia, y los sufrimientos que él ya había sufrido,
despertó gran interés en las mentes de los Amigos a su favor.
Muchos llegaron de distancias considerables a visitarlo en la prisión,
pero a muy pocos se les permitió verlo.
Los que lo hicieron, fueron obligados a comprar el permiso del carcelero,
y entonces fueron muy abusados, y se les permitió permanecer en su compañía,
pero por muy poco tiempo.
En una carta escrita a un amigo, poco después de la sesión judicial,
él narra algunos de los ultrajes a los que él fue sometido, y así concluye la narración:

[.embedded-content-document.letter]
--

Aquí soy mantenido como prisionero; pero soy el hombre libre del Señor,
y sé ciertamente que Él juzgará y vengará mi causa sobre mis adversarios.
Y así descanso confiadamente en Él, que no me dejará ni me desamparará,
por quien sufro cadenas, en el tiempo de Su buena voluntad y placer.

--

Pero mientras aquellos que deseaban consolarlo y aliviarlo, fueron abusados y expulsados,
los que iban a insultarlo y a despreciarlo, se les permitía entrar libremente.
Estos fueron incluso instados por la esposa del carcelero,
quien manifestaba un espíritu amargado hacia Parnell,
dirigiendo a menudo a su hombre a golpearlo, y frecuentemente golpeándolo ella misma.
Tal era su enemistad contra esta víctima inocente y sin resentimiento,
que ella a menudo maldecía diciendo que "`ella tendría su sangre,
o él tendría la suya.`" A lo que James Parnell le contestaba: "`Mujer,
yo no quiero la suya.`"

Algunas veces ellos se negaban a darle su comida;
otras veces ellos ponían a los prisioneros a robarle la comida cuando se la traían.
Algunos de sus amigos proveyeron una "`cama nido`" para su uso,
pero ellos se negaron a permitirle tener esta comodidad,
y él fue obligado a acostarse en las piedras,
que en la temporada de lluvias se inundaban.
Al principio, se le permitió una habitación,
por la que él pagaba cuatro peniques por noche,
pero al final no le permitieron ni siquiera eso.
Las paredes del castillo eran excesivamente gruesas,
con dos filas de agujeros abovedados; y en uno de esos huecos,
que parecía como un horno de panadero, pusieron a Parnell.
Este agujero estaba a doce pies del piso,
y la escalera que se le dio a él tenía solo seis pies de largo,
así que él se vio obligado a subir los restantes seis pies por una cuerda.
El carcelero incluso no le permitía usar una canasta ni una cuerda para subir su comida,
sino lo obligaba a ir por ella en cada ocasión. Al vivir en esta miserable,
fría y húmeda situación, sus miembros se entumecieron, y en una ocasión,
tratando de regresar a su agujero, a él le fallaron sus pies y cayó al suelo,
recibiendo una herida tan severa que fue tomado por muerto.
Pero el implacable carcelero no tuvo piedad,
y lo colocó en otro pequeño agujero llamado "`el horno,`" más abajo.
Aquí no había ventana ni puerta, y cuando la puerta estaba cerrada,
apenas tenía aire o luz.
Cuando se hubo recuperado un poco de su caída, todavía estaba estrechamente confinado,
y no se le permitía salir por aire.
En una ocasión, la puerta de su agujero se quedó abierta, y él caminó por el patio.
Pero al verlo el carcelero lo dejó afuera toda la noche en el fuerte invierno.

En medio de todo este sufrimiento él no se descuidó de sus Amigos, sino,
como ha dicho Stephen Crisp,
"`trabajó para la edificación de los que estaban convencidos,
y vio el deseo de su alma acerca de muchos,
porque él vivió para ver la semilla que había sembrado, multiplicada y crecida,
para su refrigerio.`"
Tampoco sus Amigos se olvidaron de él, sino que trabajaron fervientemente para obtener,
si era posible, una mitigación sobre su severo y cruel sufrimiento;
pero todos sus esfuerzos fueron en vano.
Entonces se podría haber dicho,
como se dijo de los primeros miembros de la Iglesia de Cristo:
"`Vean cómo estos cristianos se aman,`" porque uno de sus Amigos, Thomas Shortland,
se ofreció a estar en la prisión, cuerpo por cuerpo,
para que Parnell pudiera tener la libertad de ir a la casa de un Amigo,
hasta que se recuperara,
prometiendo que su cuerpo sería devuelto si él moría. Pero esto fue rechazado,
como también un bono de cuarenta libras, ofrecido por otros dos Amigos.

En este estado de sufrimiento y penurias, vivió alrededor de unos diez u once meses;
pero después de un tiempo su constitución empezó a hundirse bajo ello.
Parece que hacia la última parte de su encarcelamiento, a dos Amigos,
Anne Langley y Thomas Shortland, se les permitió visitarlo.
Estos fueron testigos de su pacífico cierre, y su fe permaneció inamovible hasta el final.
Él les expresó su sentido de que "`moría inocentemente`" y dijo: "`Ahora debo irme;
esta muerte debo morir.`"
Además dijo: "`He visto grandes cosas.`"
Sus últimos momentos parecen haber sido notablemente tranquilos.
Les pidió a sus amigos "`que no lo detuvieran, sino que lo dejaran ir,`" y luego,
diciendo: "`ahora me voy,`" se estiró y cayó en un dulce sueño,
y habiendo dormido una hora, no respiró más.

Así murió uno, que en la misma mañana de sus días,
había entregado su corazón a las visitas del Espíritu Santo, y a través de la fe,
la paciencia y la obediencia constantes,
se convirtió en un poderoso instrumento en la mano del Señor,
para reunir a muchos en el verdadero descanso del redil del Redentor.
Fue enterrado en el patio del castillo,
donde otros prisioneros eran comúnmente enterrados,
porque el carcelero se negó a entregar el cuerpo sin honorarios.

La malicia de sus enemigos, sin embargo, no terminó con su vida;
sino que para encubrir su propia crueldad, y para desviar, si era posible,
la atención del carácter de alguien cuya vida y muerte habían sido un reproche para ellos
mismos (tanto como hombres y especialmente como cristianos profesantes),
difundieron laboriosamente un informe por varios medios, que decía,
que él se mató a sí mismo de hambre,
porque durante los últimos diez días de su vida no pudo tomar algún alimento,
excepto ocasionalmente un poco de leche y agua.
Tal informe, por supuesto,
no tuvo ningún peso con la parte seria y reflexiva de la comunidad, muchos de los cuales,
además de Amigos, habían estado muy interesados en sus sufrimientos,
y habían utilizado muchos esfuerzos para obtener su liberación. James
Parnell fue el primer Amigo que murió en la cárcel por su religión,
y su muerte parece haber producido una considerable sensación entre aquellos en el poder,
que declararon sentirse afligidos de que su caso no había demandado más de su consideración,
antes de que fuera demasiado tarde.

Consideré que era mejor contar los sufrimientos y la muerte de este
fiel servidor del Señor durante su último encarcelamiento,
que interrumpir la narración intercalando otros asuntos.
Puede que ahora sea bueno retroceder un poco nuestros pasos y
ver en qué se ocupó durante su riguroso confinamiento.
Los hombres tenían el poder de confinar su cuerpo,
pero no podían limitar ni controlar las operaciones de ese Espíritu
que operaba en él. Su mente estaba activa en medio de tales sufrimientos
e inconvenientes externos que podrían parecer suficientes no sólo para excusarle de
trabajar mucho por la verdad,
sino incluso para excluir la posibilidad de hacerlo.
Sin embargo, su ferviente espíritu seguía recordando la herencia del Señor,
y desde su solitaria y sufrida celda, sentía la necesidad de dirigirse a los recién convencidos,
y de esforzarse por edificar, mediante diversas cartas, aquellas iglesias que habían
sido reunidas por su mediación,
y a las que ya no se le permitía predicar la Palabra de vida.
Y no sólo su espíritu estaba interesado en favor de los creyentes,
sino también en favor de los impíos,
a quienes él exhortó a apartarse de sus malos caminos,
para que no perecieran en el día de la ira y justa retribución. Algunos de estos documentos,
escritos desde la celda de James Parnell, serán interesantes, así como instructivos.

Poco después de que él fue recluido en el Castillo de Colchester,
él escribió la siguiente epístola:

[.embedded-content-document.epistle]
--

[.blurb]
=== Unas pocas palabras a todos mis queridos amigos, en y alrededor del Condado de Essex.

Y a todos ustedes, queridos amigos, esparcidos y despreciados, a quienes el Señor,
por Su poderosa Palabra, está ahora recogiendo de las tinieblas a la luz maravillosa,
del reino de este mundo al reino de su amado Hijo;
ustedes a quienes Él está separando hacia Sí Mismo, para andar delante de Él en santidad,
para que Lo conozcan y Él pueda conocerlos en la luz de Su faz;
ustedes cuyos rostros Él ha vuelto hacia Sion,
para buscar una tierra de descanso a sus almas cansadas,
que han sido arrojadas de un lugar a otro de un monte a una colina,
en este nublado y oscuro día, buscando descanso, pero no encontrando ninguno:

Ahora el Día de la gracia ha amanecido cerca de ustedes, incluso en ustedes.
Sí, y han llegado buenas nuevas a sus almas cansadas,
por medio de las cuales se ha engendrado en ustedes un amor puro a la Verdad Eterna,
cuya Verdad ha sido declarada libremente entre ustedes por los mensajeros del Altísimo,
quienes han alcanzado al Testigo de Dios en sus consciencias,
el cual sí sella a la Verdad en sus corazones.
Él es su Maestro, a quien deben escuchar y obedecer.
Permanezcan quietos en Su luz,
y contemplen la obra que el Señor ha comenzado entre nosotros;
entonces no tendrán razón de desaliento,
aunque el mar furioso se levante y las olas furiosas crezcan, como si se tragaran todo;
sin embargo todo está limitado por el Ilimitado,
y su espuma solo traerá su propia vergüenza.

Y así como tuve un tiempo para predicar la Verdad entre ustedes,
para el convencimiento de muchos,
así ahora tengo un tiempo para sellar el testimonio
con paciente sufrimiento en la sujeción del Evangelio,
para que ustedes vean que,
no solo estamos dispuestos a predicar nuestro testimonio entre ustedes,
sino también sellarlo con paciente sufrimiento, sí, inclusive con nuestra sangre,
si somos llamados a ello, como muchos de nosotros hemos hecho en esta nación,
aunque esta se llame una tierra de libertad.
De hecho, esta es una tierra de libertad con respecto a la iniquidad,
pero la verdad y la equidad son extrañas en ella, y por lo tanto son perseguidas.
Pero ustedes que son considerados dignos de recibir a estas "`extrañas,`" felices son.
Y aunque los furiosos Sodomitas los rodeen, para obligarlos a expulsar a estas extrañas,
para que ellos puedan hacer lo que quieran con ellas, aun así,
sean fieles y no les teman,
sino más bien expulsen sus cosas más preciosas y permanezcan
en la fe del Dios de la verdad y de la equidad,
y verán a los Sodomitas heridos con ceguera, y no podrán prevalecer contra ustedes.
Pero cuando ellos estén cansados de esforzarse, serán obligados a caer en tristeza;
y así se cumplirá lo que fue profetizado de antaño,
que "`ninguna arma forjada contra los fieles prosperará;`"
pero ¡ay! de los que levanten el talón contra ellos.

Por tanto, les encomiendo a todos, en el nombre del Dios de la Verdad, a ser fieles,
valientes y audaces por la Verdad que ustedes han recibido.
Y como la han recibido, así caminen en ella;
para que no profesen más en palabra que lo que poseen en la vida;
y que la luz pueda ser predicada en sus vidas, y resplandezca en su conducta,
para la gloria del Padre de las luces y para la confusión de los paganos,
que profesan a Dios en palabras, pero en la vida Lo niegan.

Estén dispuestos a que el yo sufra por la Verdad, y no la Verdad por el yo,
(porque la Verdad siempre ha sido sellada con persecución,
desde que la generación de Caín estaba sobre la tierra),
y lleven la cruz y desprecien la vergüenza y entréguense a sufrir por la Verdad recibida,
todos ustedes que siguen al Cordero a la tierra de descanso.
A través de muchas pruebas, crecerán fuertes, audaces y confiados en su Dios,
porque Dios no se conoce, como el gran Dios que es Él, hasta el tiempo de la prueba.

Todos mantengan sus reuniones en el nombre y en el temor del Señor Dios,
esperando Su poder, en obediencia a Su luz,
la cual los reprende en sus conciencias cuando hacen mal.
Esperen en Su luz y vigilen a los enemigos que son de su propia casa,
para que conozcan la lucha entablada en sus corazones contra sus enemigos espirituales.
Así conocerán al Dios de poder manifestándose a Sí mismo entre ustedes por Su gran poder,
derribando en ustedes todo lo que se opone a Él,
y todo lo que no quiere que Él reine sobre ustedes.
Y así conocerán Su propia Semilla en sus corazones,
estableciéndolos en justicia para que lleven Su imagen;
para que Él sea su Dios y ustedes sean su pueblo.

Así, en la inmutable Verdad yo descanso, en unidad con todos los fieles,
en la gloriosa libertad de los hijos de Dios,
aunque en cautiverio externo por el bien de ustedes.

[.signed-section-closing]
Conocido por todos los que me pueden leer en espíritu,

[.signed-section-signature]
James Parnell.

--

[.embedded-content-document.epistle]
--

[.letter-heading]
A los Amigos en Essex.

[.salutation]
Amigos:

A este don de Dios, en todas sus conciencias, le hablo,
que da testimonio de Dios, y es conforme a la mente de Dios,
y está puesto en sus corazones para ser su maestro,
para enseñarles a hacer la voluntad de Dios, y a caminar según la mente de Dios,
y a distinguir entre la verdad y el error, entre lo precioso y lo vil,
y entre el que le sirve al Señor y el que no le sirve.
Este Maestro--la Luz de Cristo--ilumina su entendimiento
y les deja ver la tierra de las tinieblas,
donde está la casa de la esclavitud, donde la Semilla justa está oprimida,
y donde el hombre de pecado gobierna y la muerte domina.
Esta Luz es su guía para sacarlos de la casa de la esclavitud,
de la tierra de las tinieblas y del dominio de la muerte.
Mata al hombre de pecado,
los separa de los hijos de las tinieblas y los saca de entre ellos,
para buscar otro reino, donde es experimentado el Día perfecto,
donde el dolor y el suspiro son alejados.

Pero entonces,
ustedes deben salirse de ustedes mismos y negar su propia
sabiduría y razón y todo lo que brota del yo,
pues todo esto está en enemistad con la Luz, y se opone, argumenta y lucha contra ella,
y por la luz es condenado.
Si escuchan la voz del yo,
tropezarán en el camino y muchas piedras de tropiezo estarán delante de ustedes,
y espinas y zarzas se apoderarán de ustedes, y sus pies se pegarán en el fango.
Allí se mueven en la esclavitud y muchas dificultades
e imposibilidades aparecen ante ustedes,
con dudas, temores, preguntas, murmuraciones y quejas.
Allí surge la incredulidad y muchas tentaciones se apoderan de ustedes.
A veces son tentados a regresar y a morir en Egipto,
y a veces añoran los deleites y las ollas de carne de Egipto.
A veces piensan que Dios los ha abandonado por completo,
y a veces cuestionan la verdad misma de Dios y están dispuestos a llamarla mentira.
Allí, en sí mismos, está la mente vacilante e inestable,
y todo esto surge de las tinieblas donde el yo se levanta; todo viene al escuchar al yo.

Por lo tanto, mantengan sus mentes en la Luz, el Mensajero de Dios,
que trae el mensaje de paz y las buenas nuevas de salvación. Manténganse cerca de esto,
y conózcanlo como su maestro,
guía y consejero en todo el camino por el cual deben
pasar y en todas las cosas que deben hacer.
Permanezcan en la negación de sí mismos, y conozcan la Luz,
que conduce a un solo deseo y los saca de todos los fines egoístas.
Entonces la Luz quitará todas las piedras de tropiezo,
y los conducirá a través de zarzas y espinos, y sus pies no se pegarán en el fango,
sino el camino tortuoso será hecho recto, y el camino áspero y duro será llano y fácil.
Porque en la Luz no hay ocasión de tropiezo,
sino que evita que sus pies se desvíen y sus lenguas hablen mal, conforme la escuchan.
Y cuando vayan a la derecha o a la izquierda, clama: "`Este es el camino,
anda en él.`" Esta es la Palabra dentro de ustedes de la cual viene la fe,
que hace todas las cosas fáciles y posibles; pero "`sin fe es imposible agradar a Dios.`"
Y la fe es don de Dios, y así es esta Palabra de Verdad, de la cual brota la fe.
Esta juzgará toda murmuración, duda y queja, y todo descuido, ligereza,
lujuria y lo terrenal, y condenará el terreno de donde surgen todas estas cosas.
Y aquí el ministerio de la condenación es experimentado (el cual es glorioso en su tiempo),
por medio del cual viene el ministerio de la paz, que excede al otro en gloria.
Pero tengan cuidado de obtener estas cosas solo en la comprensión,
simplemente para hablar de ellas.
Permitan que el tiempo de silencio y paciencia tengan su obra,
durante el cual deben esperar el cumplimiento de estas cosas en ustedes.
Entonces serán capaces de leer estas cosas en el interior,
y serán manifestadas en la vida, que adorna y honra la Verdad,
y así serán vasos de honor.
Pero esto no se puede experimentar sin fidelidad;
porque "`el que está dispuesto y es obediente comerá
el bien de la tierra`" (Isaías 1:19).

Por tanto, Amigos, sean fieles a lo que en su medidas les es dado a conocer;
porque la fidelidad es de gran valor.
La fidelidad debe ser en secreto y en público,
sabiendo que todas las cosas son públicas para Dios,
quien juzgará los secretos de los hombres por Jesucristo.
Por lo tanto, el que es fiel sobre poco, es aprobado por Dios, y gobernará sobre mucho;
pero el que es perezoso es echado fuera, y lo que tiene le será quitado.
Estas cosas las han leído externamente, pero ahora apréndanlas internamente.
Léanse en la Luz, y no serán engañados; porque por la Luz sus corazones son examinados,
y por ella se manifiestan todas las cosas,
por las cuales ustedes son aprobados o desaprobados por Dios,
en todas sus palabras y acciones.
Por lo tanto, en esta Luz, pongan guarda sobre todos sus pensamientos,
palabras y acciones, para que el Justo Juez sea establecido en sus corazones,
quien condena todo engaño e iniquidad, y establece justicia en la tierra,
y verdad y equidad en las partes internas, y limpia el corazón del mal.
Que esto solo los guíe, y sea su fuente de acción en todos sus caminos y acciones.
Y entonces el yo no tendrá parte,
sino que todas las cosas se harán bajo la cruz en devoción sincera a Dios.
Entonces sólo Él es glorificado, y Su temor y asombro son puestos en el corazón,
y la lengua es frenada, la voluntad reprimida, el corazón limpiado y mantenido limpio;
porque "`lo que sale del corazón es lo que contamina.`"

Por tanto, les digo a todos: vigilen, que el Único Puro pueda ejercitar sus mentes,
quien crucificará la parte carnal y mortificará las obras de la carne,
y establecerá la pureza en el corazón y producirá el fruto del Espíritu,
el cual es el amor en una vida pura.
Aquí ustedes pueden venir a vivir y a caminar y a crecer juntos en unidad en sus medidas;
porque lo que separa de la unidad es el yo,
que hace que el amor se enfríe. Pero si permanecen en el amor de Dios, el yo es negado;
y donde el yo es admitido, el amor de Dios es negado.
Aquí encuentran al enemigo en su propia casa,
contra el cual tienen que combatir y en la Luz que descubre al yo está su poder y fuerza.
Al recibir Su Luz, ustedes reciben el poder de negar al yo en sus muchas apariencias,
y este poder concilia sus corazones de unos con otros y los lleva a una
perfecta amistad y unidad que no está en la voluntad del hombre,
sino en la naturaleza pura.
Esto será una cruz a la voluntad mundana, y el mundo no la soportará,
porque rompe la comunión, el amor y la amistad del mundo,
todo lo cual está en la voluntad corrupta de los hombres carnales.
De aquí vienen todas las costumbres, modas y tradiciones del mundo,
y toda su adoración y profesión y persecución contra ustedes,
quienes habitan en la naturaleza pura.
Pero no miren hacia afuera en lo que ellos pueden hacerles,
sabiendo que lo más que ellos pueden tomar es la vida del cuerpo.
Pero mantengan sus ojos en el Señor su Dios,
en todos sus sufrimientos y cuéntenlos como sus riquezas,
para que sean dignos de sufrir por causa de la justicia;
porque a través de muchas pruebas y tribulaciones
vendrán puros al Señor y fuertes en la fe.

Así pues, que el Señor Dios de poder, esté con ustedes,
y con Su poderoso poder los mantenga humildes y atentos en sus condiciones,
para que consideren su bien eterno por encima de todas las cosas bajo el sol.
Que cada uno camine y crezca en la Verdad que ha recibido,
muriendo diariamente a las cosas que perecen, para que vengan a morar en la vida de Dios,
fuera de las cosas creadas; y entonces se les dará el verdadero uso de ellas,
junto con la sabiduría pura, como era en el principio,
cuando el hombre estaba en el uso correcto de las cosas creadas.
Aquí el paraíso en efecto será encontrado.
Pero "`el que cree no se apresure`" (Isaías 28:16) y por "`la perseverancia
en hacer el bien,`" cosecharán si no desmayan.

Queridos amigos, fue el amor de Dios en mí, el cual habla a la Semilla en ustedes,
que me obligó a escribirles y a visitarlos con esta epístola.
Aunque mi presencia corporal es apartada de ustedes (por la voluntad corrupta del hombre),
mi espíritu no cesa de rogar a favor de ustedes,
para que el Señor por su poder (por el cual Él los ha despertado del sueño,
y ha hecho que Su testigo responda a Su Verdad) bendiga
y prospere Su feliz obra en sus corazones,
para traer a Su preciosa Semilla a gobernar y a tener dominio.
Que Su gloriosa Luz brille en su conducta, y Su hermosura aparezca en su imagen,
para que los paganos sean avergonzados y teman ante el Señor su Dios.
Y aquí, amigos míos, está mi consuelo en medio de mi cautiverio: sí,
si este cuerpo fuera sacrificado, no disminuiría mi gozo que tengo por ustedes,
en quienes prospera la obra de Dios.
Por tanto, los encomiendo a todos en el nombre del Dios viviente,
a quien ustedes profesan, a que permanezcan diligentes y prudentes en Su temor,
para que no entristezcan al Espíritu de Dios,
ni hagan que Su santo nombre sea blasfemado;
no sea que añadan aflicción a las cadenas del Evangelio.

Esto de un amigo, que es conocido en espíritu,
quien por amor de la Semilla inocente sufre las cadenas del Evangelio.

[.signed-section-signature]
James Parnell.

[.signed-section-context-close]
Desde el castillo de Colchester. Mes 11, 1655.

--

[.embedded-content-document.letter]
--

[.salutation]
Para mi querido hermano William Dewsbury en la cárcel común en Northampton,

Querido y precioso hermano en la eterna e inmutable Verdad de Dios, yo, en mi medida,
te saludo con cariño. Tú eres bendecido por el Señor, querido hermano.
Tu cuidado paternal sobre mí lo reconozco,
y tu voz es un consuelo para mí. Estoy sostenido y alimentado en medio de mis enemigos.
Gloria a Dios en las alturas,
quien me ha considerado digno de llevar las cadenas del Evangelio.

Querido hermano, me alegra oír de ti y de mi querido hermano, Thomas Stubbs, contigo,
a quienes amo en el Señor,
y al resto de mis compañeros de prisión. El Señor te ha puesto por padre sobre ellos.
Sé que tu carga es grande, porque la obra está sobre ti, pero tu gozo está en tus hijos.

Verdaderamente hay una gran manifestación en estas partes,
pero hay mucha necesidad de un ministro desde que yo fui puesto en cautiverio.
Pero yo tenía buena libertad entre ellos,
antes de que se les permitiera apoderarse de mí. Y grande fue la obra del Señor,
y se extendió mucho para mi gran consuelo.
Y ahora estas cadenas han sido muy útiles, para tocar los corazones de muchos,
y el descubrimiento del espíritu de mis perseguidores,
y la confirmación de aquellos en la Verdad que fueron convencidos.
Ellos han trabajado para hacer mis cadenas dolorosas,
pero los Filisteos no conocen mi fortaleza.
A los Amigos se les ha impedido visitarme, pero no a todos.
Nuestra tierna hermana, M. S. está aquí en prisión en la cárcel de la ciudad;
fue puesta anoche por hablarle a un sacerdote.
Ella ha estado dos veces antes de esta en una semana,
pero ellos no tuvieron poder para mantenerla ahí.

Así que el mismo poder que te mantiene, me mantenga;
y que tus oraciones sean por mí. Yo descanso contigo en la unidad fraternal,
tu tierno hermano,

[.signed-section-signature]
James Parnell.

[.signed-section-context-close]
Castillo de Colchester, 16 del mes 12, 1655.

--

[.embedded-content-document.epistle]
--

[.letter-heading]
Una Epístola a los Amigos

Todos ustedes amigos de la Luz,
aunque nosotros los que somos sus ministros y mensajeros de la Luz,
somos arrojados en prisiones, agujeros y mazmorras,
y mantenidos ahí por la voluntad diabólica y corrupta del hombre,
y que esto sea permitido por Dios, el Padre de la Luz,
para cumplimiento de las Escrituras acerca de esa generación (la cual
fue profetizada por los ministros y mensajeros de la Luz en los días antiguos,
quienes sufrieron en la misma naturaleza, por la misma generación,
por el mismo testimonio);
y aunque el Señor todavía permite que la misma generación
actúe en esta naturaleza contra nosotros,
y llena su medida de ira,
esto es para la manifestación de Su Verdad y la exaltación de Su nombre de poder.

A través de todo esto, nosotros somos conocidos y manifestados a ustedes,
que están en la Luz;
y aún los incrédulos llegan a saber y a confesar que es más grande Él que está con nosotros,
que todos los que puedan levantarse contra nosotros.
Y en todo esto nos regocijamos, y, por nuestros sufrimientos somos coronados,
y tenemos la victoria sobre el mundo externo, así como sobre el interno.
Y aunque somos arrojados en prisión,
todavía esto es establecido por el Señor por un tiempo.
Por lo tanto, Amigos, mantengan su ojo en el Señor en todas estas cosas,
y no vean al hombre, ni lo que él puede hacer, ni a favor ni en contra de nosotros.
Mantengan su ojo en Dios en todas Sus obras, y en todos Sus instrumentos,
y no habrá motivo de desánimo; porque el desánimo, los temores,
las dudas y los cuestionamientos, surgen de la mente carnal.
Pero hay un Testigo eterno en sus conciencias, el cual, por la Palabra de poder,
se ha despertado en ustedes.
Por esto somos conocidos, por esto somos reconocidos y recibidos en sus corazones,
donde nuestra unidad está firme con ustedes, que son fieles, y somos recordados,
aunque ausentes en el cuerpo.

Y este Testigo está también en los hombres del mundo, aunque no lo reciben,
ni quieren retenerlo en sus mentes.
Por esta razón ellos no nos reciben,
pero tal como el Testigo yace crucificado dentro de ellos,
por eso ellos buscan matarnos a nosotros; y esta es su condenación, la cual,
desde sus propias bocas, testificará ante Dios en contra de ellos.
Y así somos hechos un olor grato para Dios tanto en ustedes que creen,
como en ellos que perecen.
Así que ustedes que creen, préstenle atención a este Testigo,
y tengan presente Su respuesta en sus conciencias,
para que ella pueda ejercitar sus conciencias en unidad con Dios,
para que puedan permanecer en el sentido de esto y sean enseñados
y guiados a la cruz con respecto a sus propias voluntades,
para que la voluntad de Dios los guíe y no su propia voluntad.
Entonces el Testigo vivo será levantado en ustedes,
para que viva y se regocije y sea su cabeza; y lo que ha sido su cabeza pueda ser herido.
En esta manera, Amigos,
sus corazones serán establecidos y confirmados en la Verdad inmutable,
a la que son llamados para que sean hijos de la Verdad.
Así todos ustedes quienes reconocen esta voz,
manténgase cerca del Testigo en sus propias mentes y conciencias,
para que se alimenten de la sustancia viva en la mesa del Señor,
y participen de la unión y comunión de los santos.
Como cada uno de ustedes habita en su propia medida,
las cosas de Dios les serán aclaradas a ustedes, y las sombras desaparecerán.

Manténganse en casa, en sus tiendas, y pongan la vela en el candelero,
para que toda la casa sea iluminada--no sea que el
ladrón se meta en un rincón secreto y los confunda,
robe, y ponga un velo sobre su luz.
Mientras ustedes tengan la luz, permanezcan en ella, y en ella verán más luz,
para barrer y limpiar por dentro, y buscar en cada rincón,
y no permitirle a ningún enemigo permanecer en la casa.
Expulsen lo que ha estado en su seno, y permítanle al Cordero estar ahí, quien ha dicho:
"`Aquel que ama algo más que a mí, no es digno de mí.`" Así que traigan todo a la Luz,
y ay de aquél que se esconda de la Luz, porque el Día lo manifestará.

¡Oh, no descansen por encima de la Vida, ni se alimenten de nada debajo de ella!
Sigan la Luz, la cual guía sus mentes hacia el Hijo; porque en Él está la paz, sí,
la paz verdadera, la cual no puede ser quebrantada.
Él es el vínculo de la paz.
Si ustedes permanecen en Él, Él permanecerá en ustedes y producirán fruto abundante.
Él los refrescará con el rocío celestial, y florecerán como en un día de verano, sí,
como plantas de justicia.
Pero la primavera viene primero.
¡Oh, cuán agradable y bella es la primavera en un campo estéril,
donde la esterilidad y la muerte desaparecen!
Cuando llega la primavera, el invierno se despoja de su abrigo, y el verano se acerca.
¡Oh, esperen ver y leer estas cosas adentro!
Ustedes que han sido estériles y muertos y secos, sin savia,
para ustedes el Sol de justicia se levanta con salvación en sus alas,
y empieza a brillar en sus costas.
Porque este es el Día en el que el Señor viene a visitarlos; sí,
a ustedes que han permanecido sentados en las tinieblas, ahora la luz ha brotado.
¡Oh, pongan sus ojos en el manantial secreto! ¡Cuiden las plantas tiernas!

Ahora ustedes están llamados a cuidar y a mantener el jardín;
no dejen que las malas hierbas y las plantas silvestres permanezcan.
La obstinación es una mala hierba; la ira es una mala hierba;
el amor propio y voluntad propia son malas hierbas; el orgullo es una planta silvestre;
la codicia es una planta silvestre; la ligereza y la vanidad son plantas silvestres;
y el deseo es la raíz de todo.
Estas cosas se han alojado en su jardín, y han sido grandes y fuertes; y la verdad,
la inocencia y la equidad, han sido dejadas,
y no pudieron ser encontradas hasta que el Sol de justicia surgió,
y encontró lo que estaba perdido, y trajo de vuelta lo que había sido expulsado.
Por lo tanto no permanezcan ociosos, sino entren a la viña y trabajen.
Su trabajo será vigilar y mantener lejos las aves del aire, las bestias inmundas,
los osos salvajes y los zorros sutiles.
Y Él, que es el Sembrador, arrancará las plantas silvestres y las malas hierbas,
y hará un muro alrededor de las vides.
Él les dirá a ustedes qué hacer.
Él, que es el Padre de la viña, estará cerca de ustedes.
Ahora, lean adentro, o tropezarán; y lo que no está claro para ustedes, espérenlo,
sabiendo que "`El que cree, no se apresure.`"
Pero ustedes que están cubiertos solo con hojas de higuera,
el Hijo los examinará. Ustedes deben llegar a la caída de la hoja,
al tiempo de la muerte y del invierno,
antes que la vida aparezca y se abran los manantiales vivientes.
Ustedes deben despojarse de sus propias vestiduras,
y entonces el Hijo los vestirá--pero no antes de que ustedes sean desnudados.
Porque verdaderamente, la vergüenza debe llegar a toda carne,
y ustedes no deben tener ni siquiera un delantal
de hojas de higuera para cubrir su desnudez.

[.signed-section-signature]
James Parnell

[.postscript]
====

+++[+++Esta epístola no tiene fecha,
pero no hay duda de que fue escrita desde el castillo de Colchester.]

====

--

La siguiente carta lleva la última fecha de cualquiera de los escritos de James Parnell,
hasta donde he podido descubrir.
Fue escrita aproximadamente a los cinco meses desde el momento de su primer encarcelamiento;
pero como había muchas cartas escritas por él durante su confinamiento
en el castillo de Colchester las cuales no se han conservado,
probablemente esta no es la última que él escribió: esta está dirigida a:

[.embedded-content-document.epistle]
--

[.salutation]
Mis queridos Amigos, hermanos y hermanas en la ciudad de Londres:

Mi amor fluye de la vida hacia ustedes que son convertidos
y renovados en corazón y mente;
separados y redimidos de entre los hijos de este mundo,
y de las contaminaciones y abominaciones en que ellos viven;
en quienes están establecidas las obras de la nueva creación, en donde mora la justicia.
Mi amor fluye de la vida hacia ustedes que son hermosos por dentro, adornados por dentro,
bellos por dentro, purificados y limpiados por dentro,
por la preciosa Sangre del Cordero, con quien son crucificados--que están en Él,
que se han puesto el vestido de bodas,
y son admitidos a la mesa del Señor y son participantes de la santa unión.

Oh, benditos del Señor, ustedes niñitos e hijos del Altísimo,
quien habita en pureza y reina en majestad,
que ha establecido y puesto Su trono en sus corazones--en
ustedes es mi gozo y gran deleite.
Sí, yo recuerdo cuando ustedes eran tiernos y acababan de brotar, pero ahora,
al esperar en el Señor,
han renovado sus fuerzas y mi gozo es pleno en ustedes y son preciosos a mis ojos.
Ustedes se han convertido verdaderamente en Judíos en lo interno,
en la circuncisión del corazón, redimidos de parientes, lenguas, lenguajes y personas,
y que han venido a la Jerusalén celestial para adorar al Padre en Espíritu y en verdad.
Él los ha escogido para llevar Su santa imagen (que ha sido tan desfigurada en
el mundo) y en ustedes exaltar y glorificar Su santo nombre entre los paganos,
y en los que no Lo conocen en este Día,
en el cual Él está visitando la tierra con juicio y con misericordia y con gran poder,
para llamar a cuentas a los habitantes de la tierra.

Bienaventurados los que han escuchado Su voz, porque cantarán y se regocijarán,
cuando otros lloren, se lamenten y aúllen.
Aunque ahora sus porciones entre ellos sean sufrimientos, desprecios, burlas, deshonras,
maledicencia, injurias, persecución, azotes y encarcelamientos, sin embargo,
han aprendido a contar estas cosas como riquezas,
quienes conocen al Consolador adentro y a su Redentor viviendo con ustedes.
Yo me regocijo en todas estas cosas, siendo ahora hecho partícipe de ellas.
¡Oh cuánto anhelo ver sus rostros, pero en eso yo estoy restringido por un tiempo!
Mi vida está ligada a muchos de sus corazones, lo cual hace que no pueda olvidarlos,
aunque mi cuerpo es mantenido por estrechas cadenas.
Pero las cadenas serán rotas por Aquel que es mi único guardador y partidario,
cuando Él haya perfeccionado Su alabanza en ellos.

¡Oh, palomas sencillas, que se sientan sin engaño en sus bocas! ¡Oh,
cómo soy arrebatado con el amor de ustedes cuando los veo en el espíritu!
Ustedes que se han entregado a la muerte, al hambre, a la espada y al fuego,
y han sido pacientemente sometidos a la voluntad del Padre
y sacrificado voluntariamente sus cosas preciosas.
Su fe es para ustedes imputada para justicia,
y el Dios en quien han confiado y creído los hará ricos en Él,
y les dará sustancia incorruptible y una herencia que nunca se desvanece.
Según sus medidas,
ustedes pueden poner sus sellos a lo que ahora les es escrito a ustedes.

Pero algunos han escuchado al espíritu maligno,
que ha traído malas noticias de la buena tierra.
Estos se han vuelto a Egipto y se han unido con sus magos
para endurecer el corazón de Faraón contra el inocente,
y llenaron la boca de los paganos con discursos blasfemos.
Pero dejen que sigan adelante; "`El que es inmundo, sea inmundo todavía;`" (Apocalipsis
22:11) porque el Señor viene rápidamente, cuya recompensa es con Él,
para dar a todos según sus obras.
Pero todas las cosas "`les ayudan a bien,`" a los que permanecen en la fe,
y que no se mueven con los vientos que soplan,
ni con las tormentas que vienen contra ustedes,
que mantienen la mirada en la mano de la Providencia en todas estas cosas.
Esto saca lo bueno del mal, para todos los que permanecen en la Verdad y no se desvían.

Por lo tanto, así como ustedes Lo han probado, sentido, conocido y experimentado a Él,
confíen en Él y permanezcan en su fe segura,
la cual es engendrada en ustedes por Su Palabra.
Sean como luces en el mundo oscuro, tanto por palabra como por conducta,
para que en todas las cosas sean aprobados por el Espíritu del Padre en sus conciencias,
como fieles y obedientes hijos, cada uno en su vocación a la que es llamado,
para que puedan obtener el premio al final de su carrera.
¡Oh! levanten sus cabezas, y miren hacia el Padre,
y vean cómo Él ha sido tierno para con ustedes,
y cómo Su amor se ha ofrecido a ustedes todo este tiempo,
que no los ha dejado sin instructores ni padres cuidadosos,
que los han vigilado con tierno cuidado.
Con mucho amor y ternura me siento atraído hacia ustedes en amor, pequeños,
que brotan de la raíz de la Vid, porque ustedes llevan la imagen de mi Padre.
He esperado mucho tiempo para escribirles, y justo ahora tuve una oportunidad,
que me hizo visitarlos con esta epístola; pues muchas veces han estado en mi recuerdo,
aunque no pude escribirles.
Y ahora deben leerme en ese amor,
que la lengua no puede expresar y en esa epístola que está escrita en sus corazones,
sin papel ni tinta, por la Palabra inmortal de vida, y allí conocerán mi nombre.

Por tanto, el Señor Dios Todopoderoso, el guardador de Israel,
los cubrirá con su sombra y los mantendrá puros e inocentes en Su santa presencia,
para que manifiesten Su alabanza en la tierra y resplandezcan como hijos e hijas de Sion.
Los encomiendo a su bendita protección,
yo que sufro en cadenas externas por la voluntad de los hombres,
por causa de la Semilla inocente, pero que estoy en libertad con los fieles.

[.signed-section-signature]
James Parnell.

[.signed-section-context-close]
Escrito desde el Castillo de Colchester,

[.signed-section-context-close]
El 12 del primer mes, 1656.

--

Estas cartas llevan un sello precioso,
las cuales evidencian al escritor como un verdadero hijo de Dios a través de Jesucristo.
No podemos dudar, como lo observó Thomas Bayles respecto a él,
que "`fue odiado y perseguido por amor a la justicia y por testificar
contra la grosera hipocresía de ese día.`" El espíritu cruel,
amargo e implacable de persecución,
que sus enemigos manifestaron y ejercieron durante tanto tiempo hacia él,
muestran claramente que eran hijos de aquella Babilonia,
de quien se profetizó que se embriagaría con la sangre de los hijos del Señor. Toda
la dedicación de James Parnell al servicio del Señor--su mansedumbre bajo el error;
su paciencia bajo el sufrimiento e insulto;
la firme integridad de su corazón durante un largo período, no sólo de sufrimiento,
sino de amargo sarcasmo y sometimiento a las burlas y bromas de hombres perversos,
de su ferviente amor a los hermanos mientras estaba
en cadenas y del tierno suspiro de su misma alma,
para que ellos pudieran, por obediencia a la Luz recibida,
llegar a conocer a Dios y a Su Hijo verdaderamente,
y morar siempre bajo el ala protectora del amor infinito--todo
esto manifiesta que él era un hombre redimido del mundo,
y ofrece la más fuerte seguridad de que "`por medio de muchas tribulaciones
él ha entrado en el reino de los cielos`" y ahora está usando la corona
prometida a todos aquellos que son "`fieles hasta la muerte.`"
