== Apéndice

[.chapter-subtitle--blurb]
Acerca del Castillo de Colchester El lugar de encarcelamiento y muerte de James Parnell

Los siguientes detalles respecto al castillo de Colchester,
resumidos en un reporte amablemente proporcionado por un Amigo de Colchester,
no serán indiferentes para el lector:

[.small-break]
'''

Testing.

"`El actual Castillo de Colchester es tan evidentemente Romano,
que no cabe duda que fue erigido después de la conquista,
cuando se construyeron fortalezas en las ciudades más importantes de Inglaterra,
con miras a una más completa subyugación de los habitantes.
Este estuvo durante muchos años en posesión de la Corona,
y después pasó por varias manos privadas,
una de las cuales trató de derribarlo por sus materiales,
pero el cemento de las paredes parecía ser de tal resistencia y solidez
que la venta de los materiales no era probable que pagaran los gastos.
Así que quedó de pie, aunque muy desfigurado.

Ahora está muy escondido por las casas circundantes,
y escaparía de la vista de un viajero que pasara e ignorara su lugar.
La estructura es cuadrada, y flanqueada en los ángulos por torres fuertes y una vez altas.
Ocupa una superficie de más de medio acre.
Sus paredes tienen casi doce pies de espesor en el sótano y once en el piso superior.
En la pared occidental hay dos hileras de celdas singulares o nichos,
que parecen haber sido cavados de la pared; tienen unos diez pies de alto,
cuatro pies de ancho y tres pies de profundidad.
Éstos, tal vez, fueron construidos anteriormente de frente,
y podrían haber sido utilizados como mazmorras solitarias.
No cabe duda, digo yo,
que una de estas celdas sirvió como la última morada de James Parnell.

Parece que Guillermo Sewel había visitado el Castillo,
probablemente con la idea expresa de ver "`el agujero,`"
en el cual esta víctima inocente estuvo confinada.
Él describe las celdas, como se mencionan más arriba:
"`dos hileras de agujeros abovedados.`"
En el momento de su visita, el recuerdo de James Parnell debía haber sido fresco todavía,
de modo que su testimonio es casi tan valioso como el de un testigo vivo.
Las dimensiones de la celda eran tan pequeñas,
que apenas le hubiera permitido a James Parnell, aunque de muy pequeño tamaño,
extenderse en toda su longitud.
Sus brazos estirados probablemente tocarían las paredes opuestas, en todas direcciones.
Esto nos dará una idea de la miseria y de la incomodidad de su situación externa.
Pero tenemos evidencia abundante y alentadora de que, en esta celda solitaria,
disfrutó de la comodidad y el apoyo de la presencia de su Salvador; y,
como Pablo y Silas,
tenía un canto de alabanza puesto en su boca en medio de sus enemigos.`"
